### ISSUE TITLE
Several platform questions

### ISSUE THREAD

**Issue by HighOnDrive** [elm-lang/elm-platform#101]
Saw Elm in the presentations at Reactive 2015, very impressive. 

Just a couple questions:

• Is there support for the HTML5 2D Canvas element?
• Can standard NPM packages be used?
• Does Elm work with React Native?

Thanks :-)

**Comment by jvoigtlaender** [comment]
The issues page in this repository is used for reporting and tracking problems with the Elm installers.

For questions like yours, the mailing list/forum https://groups.google.com/d/forum/elm-discuss is more appropriate.

**Comment by HighOnDrive** [comment]
It was easier to just dig up the info I requested, since I have no time to work through elaborate delays. Looks like no, no and no are the answers to each of my questions :)
