### ISSUE TITLE
Building from source on AppVeyor

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-platform#105]
We currently have Travis tests that build the Elm Platform from source and upload the resulting binaries to Bintray, for both 64-bit Linux and 64-bit OS X.

We do not have this as part of our AppVeyor Windows tests yet, because installing GHC 7.10 on Windows using only the command line is proving to be a Herculean effort.

Failed approaches I've tried so far on the [`build-windows`](https://github.com/elm-lang/elm-platform/tree/build-windows) branch:
- [Attempt 1: Use Chocolatey](https://github.com/elm-lang/elm-platform/blob/ffb4b7e437c8beae0bba30a0e0fc9169ef767394/appveyor.yml) - Use [Chocolatey](https://chocolatey.org/packages/HaskellPlatform) (basically Homebrew for Windows) to install GHC and Cabal. This fails because their 7.10 formula points to an obsolete URL; evidently the Haskell Platform folks decided to move their binaries and did not leave a redirect behind. I filed a bug with Chocolatey, but it's unclear if/when that will bear any fruit.
- [Attempt 2: Install Haskell Platform](https://github.com/elm-lang/elm-platform/blob/80441b0c93079fa6025dcdfff668f746080535f1/appveyor.yml) - Since `choco` was doing this, I figured I'd try doing it directly. [It didn't work](https://ci.appveyor.com/project/rtfeldman/elm-platform/build/1.0.146), presumably because the Haskell Platform is a GUI installer. I guess Chocolatey does some magic to make that work from the command line?
- [Attempt 3: Install ghc and cabal binaries](https://github.com/elm-lang/elm-platform/blob/3f1f777f0ce8499431410348cc99f1aec7c21fb2/appveyor.yml): Download the `ghc` and `cabal` binaries and add them to the PATH. This [failed](https://ci.appveyor.com/project/rtfeldman/elm-platform/build/1.0.140) when trying to install dependencies, evidently because Cabal was not up-to-date, but adding a `cabal update` step [failed](https://ci.appveyor.com/project/rtfeldman/elm-platform/build/1.0.143) with a big exit code and no explanation, even with the `--verbose` flag. This appears to be a dead end.

The next thing I'm going to try is taking this PowerShell script (which purports to install GHC 7.8 from the command line) and updating it to work for GHC 7.10: https://github.com/melted/getghc/blob/master/get-ghc.ps1

**Comment by jvoigtlaender** [comment]
Here are two further options. I haven't worked with either, but somehow I hope one of them might just work:
* https://github.com/fpco/minghc/blob/master/README.md#using-the-installer
* https://github.com/commercialhaskell/stack/blob/master/doc/install_and_upgrade.md#manual-download

I'd probably try the second one first.

**Comment by jvoigtlaender** [comment]
Note that the second option of the above does indeed install GHC, and that its README features an Appveyor badge: https://github.com/commercialhaskell/stack/blob/master/README.md

**Comment by rtfeldman** [comment]
Damn, should have mentioned I tried those already.

* MinGHC is a GUI installer and doesn't work on the command line.
* Stack installs GHC and Stack, but not Cabal. I have GHC and Cabal installing properly; it's that `cabal update` fails, which their build chain unfortunately doesn't help with. :cry:

**Comment by jvoigtlaender** [comment]
Maybe this is naive, but shouldn't it be possible, with the `stack` option, to get `cabal` working as well?

Indeed, [this comment](https://github.com/commercialhaskell/stack/issues/1149#issuecomment-149922457) suggests that `stack install cabal-install` should give you a way to `cabal` usage after going with the Stack option for getting GHC itself.

**Comment by rtfeldman** [comment]
Ooh! That sounds promising. I'll give that a try, thanks!

**Comment by rtfeldman** [comment]
Well, I was making good progress with the `stack` approach until I woke up this morning to this:

<img width="848" alt="screen shot 2015-11-15 at 9 53 47 am" src="https://cloud.githubusercontent.com/assets/1094080/11170076/e1c56bec-8b7e-11e5-947b-1e71ef5075af.png">

Guess I gotta wait until they sort that out. :stuck_out_tongue:

**Comment by rtfeldman** [comment]
@jvoigtlaender made some good progress with your `stack` suggestion, but not sure what to make of this error...any ideas? https://ci.appveyor.com/project/rtfeldman/elm-platform/build/1.0.199/job/ss4ub63l5sbj1v38

**Comment by jvoigtlaender** [comment]
Into the blue: Maybe `cp` (on that setup) likes `.cabal-sandbox/bin/elm*` better than `.cabal-sandbox\bin\elm*`? (Note the direction of slashes.)

**Comment by rtfeldman** [comment]
Oh I think you're right about that (and I started a new build trying out your suggestion), although I'm more concerned that things are not going right before that happens; `cabal` runs way too quickly and says this:

![screen shot 2015-11-19 at 10 16 43 am](https://cloud.githubusercontent.com/assets/1094080/11279755/3fc10758-8ea7-11e5-97e5-15a851851352.png)

**Comment by jvoigtlaender** [comment]
I don't know much about `stack`. But what might happen here is that the line
```
..\stack runghc BuildFromSource.hs %ELM_VERSION%
```
lets `stack` call `ghc` on its (`stack`'s) terms, and maybe those terms involve setting `GHC_PACKAGE_PATH`.

Have you tried replacing the above by something like the following?
```
the/path/where/stack/has/installed/my/ghc/bin/runghc BuildFromSource.hs %ELM_VERSION%
```

**Comment by rtfeldman** [comment]
Progress! Now `cabal` gets set up properly and the install script runs, but there's the dreaded "trying to build the network library on Windows" in the way now: https://ci.appveyor.com/project/rtfeldman/elm-platform/build/1.0.215/job/brt9efpdor4f7j6v

**Comment by jvoigtlaender** [comment]
I guess you have alread seen posts like this: http://blog.johantibell.com/2011/01/setting-up-haskell-development.html, purportedly meant to make `network` installable on Windows?

**Comment by evancz** [comment]
Subsequent work should be tracked elsewhere
