### ISSUE TITLE
Tell users what they need in addition to use elm-repl

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-platform#115]
People installing Elm stuff by following the directions from the README here will not currently learn about the fact that they need node.js in order to use `elm-repl`.

Probably:
* either that info should be added here,
* or people should be pointed to somewhere in https://github.com/elm-lang/elm-repl where that info is kept.

In addition to being told about node.js, they might also need to be told about other things (like this: https://github.com/elm-lang/elm-platform/issues/113#issuecomment-158679220). So it makes sense to collect such information in only one place, but then link to that place from another place (or places).

**Comment by jvoigtlaender** [comment]
One of the other places from where people might need to be linked to a collection of "`elm-repl` requirements", in addition to from the README of `elm-platform`, might be: https://www.npmjs.com/package/elm

**Comment by jvoigtlaender** [comment]
Refining this:
* Maybe `node.js` need not really be mentioned. People installing via `npm` will obviously already have `node.js`. Other people will learn about the need to install `node.js` as soon as they run `elm-repl`.
* But the stuff about `libtinfo` and/or `ncurses` should be pointed out somewhere. It came up [here](https://github.com/elm-lang/elm-platform/issues/113#issuecomment-158679220), and how it came up there suggests that it is not enough to mention `libtinfo` just in the README of https://github.com/elm-lang/elm-platform. Also, there is the issue that sometimes `libtinfo` seems not to be exactly the right thing. That came up for Arch Linux in the linked comment, but also for another Linux [here](https://github.com/elm-lang/elm-platform/issues/100#issuecomment-159183403).

**Comment by ronjouch** [comment]
@jvoigtlaender as an Elm newcomer who installed via Homepage → Install → npm installer, I confirm that I didn't hear about `libtinfo` requirements until bumping into this `libtinfo.so.5: cannot open shared object file: No such file or directory` error.

The workaround mentioned by https://github.com/elm-lang/elm-platform/issues/113#issuecomment-158679220 (`sudo ln -s /usr/lib/libncurses++w.so.6.0 /usr/lib/libtinfo.so.5`) worked for me.

Running Arch Linux, and Elm 0.16.0 on node 5.4.1 + npm 3.5.3 (official packages).

**Comment by learningjs** [comment]
Thank you @ronjouch for the solution, because not even google had helped :smile_cat:

**Comment by lacriment** [comment]
@ronjouch thank you.

**Comment by evancz** [comment]
I am reading this as, **we need to tell people to install `libtinfo-dev` and `zlib1g-dev` before they build stuff**. If that is correct, it is added in https://github.com/elm-lang/elm-platform#2-actually-build-elm-things now!

**Comment by jvoigtlaender** [comment]
Actually, people usually needed `ncurses-dev`. Whether that's covered by the other one you mention, `zlib1g-dev`, I don't know.

**Comment by evancz** [comment]
When I build, I believe the `libtinfo-dev` one covers that. If we have reports of folks building on Ubuntu or something and running into issues, I'll change it to `ncurses-dev` but I'm pretty sure that's a superset.

**Comment by Philip-Nunoo** [comment]
@ronjouch wow you just saved me a lot of internet searching.

**Comment by dtonhofer** [comment]
If anyone drops by later: 

On Fedora 27, with _node v10.0.0_ (compiled from source) and _elm 0.18.0_, `elm-repl` conks out with "`... node/lib/node_modules/elm/Elm-Platform/0.18.0/.cabal-sandbox/bin/elm-repl: error while loading shared libraries: libtinfo.so.5`". 

Shared library` /usr/lib64/libtinfo.so.6` is provided by package `ncurses-libs-6.0` (try `rpm --query --file /usr/lib64/libtinfo.so.6`).

I don't know why `elm-repl` wants the old version (and does elm really use cabal?), but adding the symlink (`cd /usr/lib64; ln -s libtinfo.so libtinfo.so.5`) indeed makes `elm-repl `run (reliably...? we shall see)
