### ISSUE TITLE
`npm install` fails on Debian

### ISSUE THREAD

**Issue by vito** [elm-lang/elm-platform#119]
Debian (intentionally) installs nodejs as `/usr/bin/nodejs`, not `/usr/bin/node`.

```
+ sudo npm install -g elm
/usr/local/bin/elm -> /usr/local/lib/node_modules/elm/binwrappers/elm
/usr/local/bin/elm-make -> /usr/local/lib/node_modules/elm/binwrappers/elm-make
/usr/local/bin/elm-package -> /usr/local/lib/node_modules/elm/binwrappers/elm-package
/usr/local/bin/elm-reactor -> /usr/local/lib/node_modules/elm/binwrappers/elm-reactor
/usr/local/bin/elm-repl -> /usr/local/lib/node_modules/elm/binwrappers/elm-repl

> elm@0.16.0 install /usr/local/lib/node_modules/elm
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! elm@0.16.0 install: `node install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the elm@0.16.0 install script.
npm ERR! This is most likely a problem with the elm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls elm
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.2.0-1-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "elm"
npm ERR! cwd /home/alex/dotfiles
npm ERR! node -v v4.2.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/alex/dotfiles/npm-debug.log
npm ERR! not ok code 0
```

Relevant section from the docs it references:

```
nodejs command
--------------

The upstream name for the Node.js interpreter command is "node".
In Debian the interpreter command has been changed to "nodejs".

This was done to prevent a namespace collision: other commands use
the same name in their upstreams, such as ax25-node from the "node"
package.

Scripts calling Node.js as a shell command must be changed to instead
use the "nodejs" command.
```

**Comment by jvoigtlaender** [comment]
The remedy for this is already mentioned on https://www.npmjs.com/package/elm. So, what else do you think is necessary?

**Comment by vito** [comment]
Hadn't noticed that, thanks. I worked around it by just symlinking `nodejs` to `node`.

For anyone else who ended up here, here's a relevant SO with a bit more background: http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu

Kind of a shame to have to install a legacy package and do local workarounds, but it looks like `elm-platform` is at least consistent with other npm packages. NPM's own docs say that the `start` field will default to `node server.js`[1], which makes me think this practice is still fairly commonplace and people aren't really trying to find more portable ways to invoke JS as package.json hooks. :/

The only thing I'd really ask is that this "just works" and perhaps calls its own script which invokes `nodejs` or `node`, but I understand if you'd rather wait for a better solution from upstream - it definitely doesn't seem like something every NPM package author should have to do.

I'll close this since it's not really this package's fault. Thanks again.
