### ISSUE TITLE
Errors building 0.16 from source on OSX

### ISSUE THREAD

**Issue by anicholson** [elm-lang/elm-platform#120]
When I attempt to build elm 0.16 from source, `elm-compiler` fails to build.

[Full output of the commands](https://gist.github.com/anicholson/f0f20a2581e788155ec3)

Environment:

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3

$ cabal --version
cabal-install version 1.18.0.5
using version 1.18.1.4 of the Cabal library 
```

I'm on OSX Yosemite.

**Comment by jvoigtlaender** [comment]
Wrong GHC version. The README of this repository suggests using GHC 7.10, and indeed Elm 0.16 is known to *not* build with anything before GHC 7.10.

**Comment by anicholson** [comment]
@jvoigtlaender ah, I missed that. Thanks for such a speedy response!
