### ISSUE TITLE
Debian/Wheezy: Elm binaries imported by npm require glibc 2.15

### ISSUE THREAD

**Issue by jaredmorrow** [elm-lang/elm-platform#122]
I'm sure this is a known issue, but I didn't find it in the issues list.  I'm filing this so other people on Wheezy/sid/etc. know they are not alone.

The npm version of elm `0.16.0` requires `glibc 2.15`, but wheezy/main only goes up to `2.13` as of 12/01/2015.  I'm guessing that `https://dl.bintray.com/elmlang/elm-platform/0.16.0/linux-x64.tar.gz` which is used is built on something newer like Debian Jessie.

I know the solution is "build from source" probably at this point, but I'm not sure that is the best solution for elm as a language going forward.

I'm willing to help in any way you need to get packages built on an older linux platform to include more people/platforms.  If that is not interesting and "build from source" is the only option at this point, please feel free to close this issue.

```
# npm --version
3.5.0
# elm
/usr/lib/node_modules/elm/Elm-Platform/0.16.0/.cabal-sandbox/bin/elm: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by /usr/lib/node_modules/elm/Elm-Platform/0.16.0/.cabal-sandbox/bin/elm)
# cat /etc/debian_version
7.9
```

**Comment by dusky3** [comment]
@jaredmorrow see my comment here https://github.com/elm-lang/elm-platform/issues/63#issuecomment-145675637. I also posted the link with the instructions for upgrading glibc on debian.

**Comment by jaredmorrow** [comment]
I know how to upgrade glibc, I just don't think that is a reasonable expectation to require an upgraded libc outside of the supported packaging system.  This is the burden those of us who distribute packages bear.

I'll build from source and provide my own packages internally.
