### ISSUE TITLE
http://elm-lang.org/examples/key-presses

### ISSUE THREAD

**Issue by antalk2** [elm-lang/elm-platform#123]
http://elm-lang.org/examples/key-presses gives different results on firefox (42.0 Ubuntu)
and chromium

firefox: "The last key you pressed was: '\\0'"  for letters
chromium: "The last key you pressed was: 'a'" (for letter 'a')

chromium: arrows ignored
firefox: arrows decoded to '%' '(' '\\''  '&'

**Comment by jvoigtlaender** [comment]
You are reporting this in the wrong repository. The right repository for reporting it is the one that already has a report of this issue (https://github.com/elm-lang/core/issues/326) as well as a pull request fixing it (https://github.com/elm-lang/core/pull/435).

**Comment by jvoigtlaender** [comment]
Please close this issue.
