### ISSUE TITLE
Filenames are not being completed

### ISSUE THREAD

**Issue by dasch** [elm-lang/elm-platform#124]
I'm running Elm on Mac OS X El Capitan using zshell. When I type `elm make x` and hit tab, no autocompletions are provided. It seems that the Elm binary is blocking autocompletion, forcing me to type out the full filename every time. Is this intentional or just a bug?

**Comment by jvoigtlaender** [comment]
What happens if instead you type `elm-make x` and then hit tab?

**Comment by dasch** [comment]
Then it works.

**Comment by jvoigtlaender** [comment]
So I'd say it's an issue with your shell. That it is happy to autocomplete `$1` in `executable $1`, but not `$2` in `executable $1 $2`.

(Note that in general, the `elm` executable does nothing else than reading its first argument `$1`, then issuing a call to an assumed executable `elm-$1` with whatever remaining arguments there are on the command line. So `elm $1 $2 $3` turns into `elm-$1 $2 $3`.)

**Comment by dasch** [comment]
That could be, but autocompletion works fine for all other commands, including ones with subcommands (I use `sub` based tools a lot.) It would seem that the Elm installer added autocompletion for the `elm` command, but that it doesn't work...

**Comment by evancz** [comment]
I suspect this is related #135 about man pages. I guess some shells use man pages to guide the autocomplete, and maybe the default is to just not do things if there are no man pages.

I don't know how to fix this other than adding man pages, so I am going to close. Sorry for the trouble!
