### ISSUE TITLE
NPM Installer doesn't respect proxy environment variables

### ISSUE THREAD

**Issue by rainyday** [elm-lang/elm-platform#125]
The `https` module doesn't look for `https_proxy`/`HTTPS_PROXY` so install.js fails when run on a system behind a proxy server. It's possible to pass proxy options to `https.request` but this has problems with http proxy -> https which is how most corporate proxies are set up so it may worth it to switch to the `request` module from npm.

**Comment by tfga** [comment]
+1

**Comment by FrontierPsychiatrist** [comment]
+1

**Comment by rtfeldman** [comment]
I'm not familiar with this problem. Can you provide steps to reproduce for someone who is not behind a proxy server? (Or a quick fix, if one exists?)

**Comment by FrontierPsychiatrist** [comment]
@rtfeldman I opened #130 that uses `request` as @rainyday suggested.

Sadly I cannot provide steps to reproduce this behind a proxy as I don't know how to administer a Windows/Linux system to only allow proxied requests.

**Comment by tfga** [comment]
It works! :)

Thanks! :+1:

**Comment by evancz** [comment]
Not certain this is resolved, but it sounds like it. Open a new thing if there are still problems!
