### ISSUE TITLE
elm win installer with trojan horse

### ISSUE THREAD

**Issue by neocris** [elm-lang/elm-platform#129]
hi. i run a scan of elm 0.16 installer for windows with clamav 0.98.7 and detected Win.Trojan.Kazy-2712. has anyone seen this? possible false positive? elm 0.15 doesn't report anything

**Comment by jvoigtlaender** [comment]
@evancz, is there even the slightest possibility that malware could have sneaked into the win installer? Where's the build of the installer happening?

**Comment by evancz** [comment]
Probably should add @rtfeldman to this.

I used NSIS to create the installer, and I believe it is distributed through a rackspace file sharing service. Both of those should be pretty non-scary.

I know @rtfeldman added some additional automation, but I don't remember all the details.

**Comment by rtfeldman** [comment]
I attempted set up building the Windows binaries from source automatically on a CI server (like the Linux and OS X binaries now are), but got stuck on [`cabal install`ing the Network library on a Windows](https://github.com/elm-lang/elm-platform/issues/105#issuecomment-159316066) server being a nightmarish productivity vortex which now haunts my dreams. :grin:

**Comment by jvoigtlaender** [comment]
My theory now is that this is a false alarm to be blamed on NSIS. Probably there is something that NSIS does that makes created binaries suspicious (looking similar to Win.Trojan.Kazy-2712) for some checkers. Support for this theory:
* https://www.herdprotect.com/dotnet.exe-199c358a7505d0627faf09c4b1030a84d7131850.aspx
* https://www.herdprotect.com/cpsetup.exe-66eb5036e5aa7d1a79ec2eada7bb374602128253.aspx

@neocris, have you observed any additional oddities? If not, I guess this can be closed.

**Comment by neocris** [comment]
@jvoigtlaender yes, it's probably a false positive, although a cross-check with other antivirus engines might be applicable here; the remained issue is, it seems to me, wasn't NSIS also used to create the installers prior to 0.16? if so why those versions don't signal any traces of kazy, if not that might be a conclusive clue to your guess.

**Comment by jvoigtlaender** [comment]
Good question, about why previous versions of the installer (also built with NSIS) are not flagged as suspicious.

**Comment by neocris** [comment]
i wish to inform that as of 13 april virus signature db (main:57;daily:21491) of clamav 0.98.7, elm 0.16 scan no longer reports any trojan infection

**Comment by CumpsD** [comment]
Happening again with 0.17

Windows defender: Trojan. Fatale.B!plock

Can anyone else verify?

**Comment by CumpsD** [comment]
Update: Later this evening, it seems to be marked as OK by Windows Defender.

I also scanned it here: https://www.virustotal.com/en/file/ddfa830a90dd72afbb33f8d9e38c7d4bdf875e9a4b6c4348526a61d8a14ae7ec/analysis/1462993185/
