### ISSUE TITLE
Elm not installing on Arch linux

### ISSUE THREAD

**Issue by neunenak** [elm-lang/elm-platform#13]
Using the arch-specific directions, installing haskell-elm from the AUR fails in the linking stage after compilation, with the error:

usr/bin/ld: cannot find -lHSunion-find-0.2
/usr/bin/ld: cannot find -lHSconcatenative-1.0.1
collect2: error: ld returned 1 exit status

**Comment by evancz** [comment]
Arch specific instructions have been gotten rid of. Not sure if this is still an issue.
