### ISSUE TITLE
Provide official ARM build

### ISSUE THREAD

**Issue by rosenk** [elm-lang/elm-platform#131]
On Raspberry Pi 2:
`npm -g install elm`
`Unfortunately, there are currently no Elm Platform binaries available for your operating system and architecture.`

Building from source is a horrific experience on such slow device. I tried but ghc is running out of ram or something.

**Comment by mgold** [comment]
Here's a workaround: you don't have to compile on the Pi. Compile your Elm to JS on a "real computer", and then copy the JS to the Pi.

**Comment by hoosierEE** [comment]
ARM computers _are_ real computers. :stuck_out_tongue:  But +1 from me anyway.

**Comment by category** [comment]
@mgold Re the JS files, which ones are to be copied? So far I have

```
# find / -name "elm" 2>/dev/null
/usr/lib/node_modules/elm
/usr/lib/node_modules/elm/Elm-Platform/0.16.0/.cabal-sandbox/bin/elm
/usr/lib/node_modules/elm/binwrappers/elm
/usr/bin/elm
/root/.npm/registry.npmjs.org/elm
/root/.npm/elm
```

**Comment by mgold** [comment]
Not Elm itself, but the result of compiling an Elm program. By default this is `index.html` but can be changed with `--output`. If you supply a filename ending in `.js` the compiler will output only JS and not HTML.

**Comment by category** [comment]
Ah I see - thanks - out of necessity I've been using that method in my workflow.

**Comment by evancz** [comment]
I can't commit to supporting ARM builds on my own. I know @rtfeldman has done work on automating the creation of binaries, so if we can figure out how to make ARM versions, that'd be great!

I don't think keeping this issue open will make that outcome more or less likely, so I am going to close.

**Comment by johannesl** [comment]
+1 on this if it makes any sense for such a comment.

**Comment by daniel-kun** [comment]
Too bad that Elm can not be used on a Raspberry Pi :-(

**Comment by gabethexton** [comment]
Sharing @daniel-kun 's Raspberry Pi solution... https://dev.to/danielkun/using-elm-on-a-raspberry-pi-42pi
