### ISSUE TITLE
REPL does not work if elm npm is installed locally

### ISSUE THREAD

**Issue by xarvh** [elm-lang/elm-platform#132]
As non-root user, run `npm install elm`, then run it from the local `node_modules` directory:
```
nw@glue ~$ ./node_modules/.bin/elm repl
Could not find command `repl`. Maybe there is a typo?

Default commands include:

  make      Compile an Elm file or project into JS or HTML
  package   Manage packages from <http://package.elm-lang.org>
  reactor   Develop with compile-on-refresh and time-travel debugging
  repl      A REPL for running individual expressions

When you try to run the command `repl` we actually search for an
  executable named elm-repl. Are you able to run elm-repl?
  Is it on your PATH?
```
(Using npm 2.14.12 on Linux)

When installed with `sudo npm -g install elm` the repl will run normally.

Npm executables installed via non-root `npm install` should work normally, without assuming they have been installed globally (not everyone has root access...)

**Comment by evancz** [comment]
I'd recommend calling `./node_modules/.bin/elm-repl` directly. Notice the extra `-` in there. The way the `elm` binary works is that it looks around your PATH for things named `elm-whatever` so I don't think there is a nice fix for this.

**Comment by habibalamin** [comment]
Would adding the working directory of the `elm` process (i.e., where the running `elm` binary is located) to the list of paths to search through be an acceptable solution to this problem?
