### ISSUE TITLE
Cannot install the dependency

### ISSUE THREAD

**Issue by h87kg** [elm-lang/elm-platform#133]
```
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 3.0.0
    evancz/elm-effects 2.0.1
    evancz/elm-html 4.0.2
    evancz/start-app 2.0.2
    evancz/virtual-dom 2.1.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core
failed with 'InternalIOException recv: resource vanished (Connection reset by peer)' when sending request to
    <http://github.com/elm-lang/core/zipball/3.0.0/>
```

**Comment by jvoigtlaender** [comment]
Just a wild guess: Are you trying this from China? There was someone running into I think exactly this problem recently, and the cause seemed to have been the great firewall.

**Comment by h87kg** [comment]
@jvoigtlaender You're right. But how can I fix it.

**Comment by jvoigtlaender** [comment]
Maybe ask @yuffiy? I found the case I was remembering above. It was this: https://github.com/elm-lang/elm-package/issues/190#issuecomment-188791531, so maybe @yuffiy had a solution.

**Comment by yuffiy** [comment]
@jvoigtlaender 

This error is about network failure for most China developers. Use proxy or VPN can fix it. But It's too much trouble. I hope the team can pay attention to this problem. 

And, I like Elm :)

**Comment by yuffiy** [comment]
@h87kg install的时候开vpn吧，

**Comment by jvoigtlaender** [comment]
@yuffiy, the question here is: What is it "the team" can do about it? The problem appears to occur when `elm-make` tries to download something from GitHub. So what would `elm-make` have to do differently for this download to work from within China?

In any case, I'll open a new issue over at the `elm-package` repository. If there are details you can provide about what exactly is not working etc., it would be good if you can weigh in there.

**Comment by jvoigtlaender** [comment]
The new issue is here: https://github.com/elm-lang/elm-package/issues/194.

@yuffiy, if you can describe the situation in more detail, please do over there.

@h87kg, please close the issue here. Follow-ups should happen in the other issue.

**Comment by h87kg** [comment]
Thanks in advance.
