### ISSUE TITLE
Elm-package install evancz/elm-html breaks environment

### ISSUE THREAD

**Issue by mlooney** [elm-lang/elm-platform#140]
As a new user, following along various hello-world examples, starting with a hello-world elm source (depending on Html module), and no elm-package.json, nor elm-stuff dir:

```
$ elm-make
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 4.0.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core
Packages configured successfully!
Success! Compiled 23 modules.
$ elm-package install evancz/elm-html
To install evancz/elm-html I would like to add the following
dependency to elm-package.json:

    "evancz/elm-html": "4.0.2 <= v < 5.0.0"

May I add that to elm-package.json for you? (y/n) y


Error: Unable to find a set of packages that will work with your constraints.
```

I fully expect i'm doing something entirely stupid, but as a new user, it's not clear what.

See attached for unmodified elm-package.json, and directory of elm-stuff.

[elm-stuff.txt.zip](https://github.com/elm-lang/elm-platform/files/257725/elm-stuff.txt.zip)

[elm-package.json.zip](https://github.com/elm-lang/elm-platform/files/257724/elm-package.json.zip)

**Comment by jvoigtlaender** [comment]
Which version of Elm do you have? What's the output of `elm-make --version` for you?

**Comment by mlooney** [comment]
elm-make 0.17 (Elm Platform 0.17.0)

**Comment by jvoigtlaender** [comment]
Congratulations, you installed the brand new version of Elm that was made available only a few hours ago (literally)!

The downside is that documentation at many places, like the tutorials you are reading probably, hasn't yet caught up with the version change. And stuff has changed. What affects you specifically is that package `evancz/elm-html` was transitioned to `elm-lang/html`. Try that.

**Comment by mlooney** [comment]
hah! thanks,  just my luck :)
