### ISSUE TITLE
Version 0.17 on Windows - elm package install fails immediately

### ISSUE THREAD

**Issue by hobbit125** [elm-lang/elm-platform#141]
Running `elm package install` in an empty directory causes an elm-package.json file to be created but immediately after, fails with the error:

`Error: Unable to find a set of packages that will work with your constraints`

**Comment by trevorriles** [comment]
I am also seeing this on OSX.

**Comment by jvoigtlaender** [comment]
Show us the contents of the `elm-package.json` file?

**Comment by hobbit125** [comment]
`{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "3.0.0 <= v < 4.0.0"
    },
    "elm-version": "0.17.0 <= v < 0.18.0"
}`

**Comment by jvoigtlaender** [comment]
The problem is the line `"elm-lang/core": "3.0.0 <= v < 4.0.0"`. Change that to `"elm-lang/core": "4.0.0 <= v < 5.0.0"` and you should be fine.

As to why `elm-package` populated this wrongly, I don't know.

 @evancz, this may be kind of an emergency: Many people might get affected by this, as the two users here were.

**Comment by evancz** [comment]
Can people try removing `~/.elm/package/` and see if this persists?

**Comment by hobbit125** [comment]
That fixed it.  (On Windows this was in ~/AppData/Roaming/elm/package)

**Comment by hobbit125** [comment]
So that worked and I installed the new html package (elm-lang/html.) Now when running the new Counter.elm example through elm-reactor, I get the following compile error:

    elm-make: CreateDirectory "elm-stuff\\build-artifacts\\0.17.0\\elm-lang\\core\\4.0.0": invalid argument (The parameter is incorrect.)

**Comment by trevorriles** [comment]
@evancz that fixed it for me.

**Comment by amcsi** [comment]
My core version is correct, I'm on windows and recursively deleting ~/AppData/Roaming/elm/package did _not_ fix it for me :(

**Comment by evancz** [comment]
@amcsi, open a new issue. Try to provide enough information for us to help out. This is not happening to anyone else it seems, so more info about your directories and OS and PATH are needed.

Otherwise, I think this is sorted out?
