### ISSUE TITLE
Error: No versions of package 'evancz/elm-graphics' were found!

### ISSUE THREAD

**Issue by amcsi** [elm-lang/elm-platform#142]
New issue from https://github.com/elm-lang/elm-platform/issues/141

When on Windows 10 and trying to get Elm 0.17 installed, I'm able to install core and html, but when I try to install evancz/elm-graphics, the package manager insists I misspelled it.

```
C:\0\tic-tac-toe>elm-package install evancz/elm-graphics

Error: No versions of package 'evancz/elm-graphics' were found!
Is it spelled correctly?
```

Also, recursively deleting ~/AppData/Roaming/elm/package did not fix it for me.

Here is my `elm-package.json` file's contents:

```json
{
    "version": "1.0.0",
    "summary": "Tic Tac Toe practice project",
    "repository": "https://github.com/amcsi/elm-tic-tac-toe.git",
    "license": "MIT",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "4.0.0 <= v < 5.0.0",
        "elm-lang/html": "1.0.0 <= v < 2.0.0"
    },
    "elm-version": "0.17.0 <= v < 0.18.0"
}
```

**Comment by amcsi** [comment]
After playing around with removing elm globally, pruning it, removing all directories where elm was installed (with the help of the `which` command), it turned out that my local project's package.json still had elm 0.16.0 in it, and thus the old 0.16.0 elm-package bin was taking precedence over the global install -.-

Updating elm in my local project's package.json and installing it fixed the issue. I'm closing this.

**Comment by genericarati** [comment]
I had similar problems while downloading elm-lang/navigation library. Even though I had latest version of elm installed globally. I reinstalled it anyway and problem was resolved.
