### ISSUE TITLE
Elm 0.17 bundles with core 3.0.0

### ISSUE THREAD

**Issue by princejwesley** [elm-lang/elm-platform#143]
Elm `0.17` bundles with core 3.0.0.

```
elm 🙈 ₹ elm repl
---- elm repl 0.17.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> 1
-- SYNTAX PROBLEM --------- elm-stuff/packages/elm-lang/core/3.0.0/src/Array.elm

I ran into something unexpected when parsing your code!

2|     ( Array
       ^
I am looking for one of the following things:

    something like `exposing (..)` which replaced `where` in 0.17
    whitespace


>
```

**Comment by jvoigtlaender** [comment]
Try deleting `~/.elm/package/` (so that Elm 0.17 can recreate it without being confused by old stuff).

Then, try `elm-repl` again, making sure you do it in a completely fresh directory.

Does the issue persist?

**Comment by princejwesley** [comment]
It works after deleting `~/.elm/package` and run the command in fresh directory.

**Comment by patamushta** [comment]
I had the same problem with 0.18 after trying to make with 0.16. I deleted elm-stuff/ directory and elm-package.json and after that remake with 0.18 and everything works just fine.
