### ISSUE TITLE
elm-make invalid JSON report

### ISSUE THREAD

**Issue by pauldijou** [elm-lang/elm-platform#148]
When using `elm-make Main.elm --warn --report=json`, it produces an invalid JSON from time to time.

**Compilation errors**

All good, it's an array containing all errors.

```elm
module Main exposing (..)

a: String
```

```json
[{"tag":"MISSING DEFINITION","overview":"There is a type annotation for `a` but there is no corresponding definition!","subregion":null,"details":"Directly below the type annotation, put a definition like:\n\n    a = 42","region":{"start":{"line":3,"column":1},"end":{"line":3,"column":10}},"type":"error","file":"Main.elm"}]
```

**Valid Elm code**

Wrong, it outputs a string which is not a valid JSON (missing double quotes). Wouldn't it be better to have the same schema every time? It could be an empty array (indicating all was fine) or it could be a more generic schema, something like `{ "status": "...", "warnings": [...], "errors": [...], "documentation": [...] }` or `{ "status": "...", "report": [...], "documentation": [...] }`.

```elm
module Main exposing (..)

a: String
a = "a"
```

```json
Successfully generated index.html
```

**Simple warnings**

Wrong, it output a JSON array followed by a kind of string. It should either be only the array or the more generic schema.

```elm
[{"tag":"missing type annotation","overview":"Top-level value `a` does not have a type annotation.","details":"I inferred the type annotation so you can copy it into your code:\n\na : String","region":{"start":{"line":4,"column":1},"end":{"line":4,"column":2}},"type":"warning","file":"Main.elm"}]
Successfully generated index.html
```

**Documentation errors**

In case of some exposed modules code, things go even more wrong. If there are warnings and missing documentation, it outputs two JSON arrays separated by a newline, which, put together, is invalid JSON.

```json
[{"tag":"missing type annotation","overview":"Top-level value `data` does not have a type annotation.","details":"I inferred the type annotation so you can copy it into your code:\n\ndata : String","region":{"start":{"line":9,"column":1},"end":{"line":9,"column":5}},"type":"warning","file":"src/Test.elm"}]
[{"tag":"MISSING ANNOTATION","overview":"The value `data` does not have a type annotation.","subregion":null,"details":"Adding type annotations is best practice and it gives you a chance to name\ntypes and type variables so they are as easy as possible to understand!","region":{"start":{"line":9,"column":1},"end":{"line":9,"column":5}},"type":"error","file":"src/Test.elm"}]
```

**Conclusion**

- It would be better to have a unique JSON schema covering all use-cases.
- Only return valid JSON, never "Successfully generated ...", add it as a property of the JSON if needed

**Comment by evancz** [comment]
I agree with this. I am hoping to make improvements to the reporting pipeline in `elm-make` eventually that will make this possible. Until then, I'd rather track progress on this myself rather than in an issue here.

Thanks for the report!
