### ISSUE TITLE
Confusing sentence in 0.17 upgrade doc

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-platform#149]
After the change @evancz just merged, there is now this sentence:
> This is a super easy change, so we will add a link to an auto-upgrade tool here when one exists.

appearing after a table that lists four changes. So which of these four is "a super easy change"? Or are all four "super easy changes" (plural) that will be supported by an auto-upgrade tool at some point?

**Comment by evancz** [comment]
I'll fix it.
