### ISSUE TITLE
Remove binwrappers from npm installers

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-platform#150]
We no longer need to set `ELM_HOME`, so we no longer need binwrappers. Removing them will solve problems like https://github.com/elm-lang/elm-platform/pull/114 - besides speeding up execution and simplifying the code base.

Instead, we should have the actual plain old binaries end up in `/usr/local/bin` or wherever - no wrappers at all.

**Comment by evancz** [comment]
I think this happened.
