### ISSUE TITLE
Certain let indent syntax not recognized

### ISSUE THREAD

**Issue by amcsi** [elm-lang/elm-platform#153]
Hey, thanks so much for the latest release. It makes elm development 10x better than before :)

There is an issue though that in the `evancz/elm-graphics` package this indenting seems to result in a syntax error in the plugin: https://github.com/evancz/elm-graphics/blob/master/src/Collage.elm#L326-L327

And that is also causing the rest of the definitions of that file to not be recognized either.

**Comment by jvoigtlaender** [comment]
What plugin are you talking about?

**Comment by amcsi** [comment]
Ah wrong repo, soz!
