### ISSUE TITLE
"elm package install xyz" refers to outdated package

### ISSUE THREAD

**Issue by DestyNova** [elm-lang/elm-platform#155]
If you specify an invalid package name, Elm will suggest `evancz/elm-html` instead of the new `elm-lang/html`:

```
elm package install wat
Uh oh, argument "wat" is not a valid PACKAGE

There should be a slash separating the user and project name (user/project)
[...]
Examples: elm package install # everything needed by elm-package.json elm
package install evancz/elm-html # any version elm package install
evancz/elm-html 1.2.0 # specific version
```
If I hadn't read the upgrade docs, my next step might have been to try to install "evancz/elm-html", which would probably not be the right thing to do.

**Comment by jvoigtlaender** [comment]
That's been fixed: https://github.com/elm-lang/elm-package/commit/6988fe4b2f0c3505c86f997b5ac8dd084892774a.
