### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by boomshroom** [elm-lang/elm-platform#16]
When doing the "Over 9000" tutorial on conditionals, I discovered that indenting the second line with spaces (or keeping on the same line in the first place) has no problems, but not indenting at all or indenting with tabs return the errors 
```
[1 of 1] Compiling Main                ( Main.elm )
Parse error at (line 2, column 1):
unexpected "e"
expecting newline or spaces
```
and
```
[1 of 1] Compiling Main                ( Main.elm )
Parse error at (line 2, column 1):
unexpected "\t"
expecting newline or spaces
```
respectively.

On an unrelated note, the "'" (apostrophe) gets rendered as "\'".

**Comment by raould** [comment]
yeah, this i find confusing as well, especially since i'm in emacs elm-mode and it is doing my indenting for me, and it is inserting tabs. oy veh.

**Comment by rtfeldman** [comment]
These are both working as intended, but certainly the error messages could use work!

I've created https://github.com/evancz/error-message-catalog/issues/14 and https://github.com/evancz/error-message-catalog/issues/15 in the Error Message Catalog repo to track these, so future versions of the compiler can better explain what's going on. Let's move further discussion there.

Thanks for reporting this!
