### ISSUE TITLE
Windows installer doesn't change the PATH

### ISSUE THREAD

**Issue by dusky3** [elm-lang/elm-platform#161]
I checked the option during the install and tried installing twice, but the installer dosn't change the PATH variable. When I run elm repl it's still 0.17 instead of 0.17.1. When I run updatepath.vbs myself I get the following error:
```
Line 2
Char: 1
Error: Subscript out of range
Code: 800A0009
Source: Microsoft VBScript runtime error

```

I run Windows 7 64bit.

**Comment by jvoigtlaender** [comment]
*Which* PATH are you talking about? The System's PATH or the User's PATH?

As far as I know, the installer tries to add Elm to the User's PATH. That might fail if your User so far does not even have a PATH setting.

**Comment by jvoigtlaender** [comment]
Actually, it's probably not that (User PATH) issue. It was fixed a while ago: https://github.com/elm-lang/elm-platform/commit/dade410ad965df4fb2810448a9ff7327fd88200f.

**Comment by jvoigtlaender** [comment]
That line (2) tries to read an argument. When you "run updatepath.vbs" yourself, do you provide it an argument?

**Comment by jvoigtlaender** [comment]
Actually, have you *checked* that the installer hasn't added Elm to the PATH? Maybe it *has* added it to the User's PATH, and the fact that running the repl still gives you 0.17 is just because the old version is on the System's PATH?

**Comment by dusky3** [comment]
> That line (2) tries to read an argument. When you "run updatepath.vbs" yourself, do you provide it an argument?

No.


> Actually, have you checked that the installer hasn't added Elm to the PATH? Maybe it has added it to the User's PATH, and the fact that running the repl still gives you 0.17 is just because the old version is on the System's PATH?

You are right, it is in the user's PATH along with the old version (0.16) which I just deleted from the PATH, but no 0.17 is there which is weird. I tried the repl in Lighttable and it uses 0.17.1. I opened the command prompt again and it still runs 0.17, but the git-bash which I have installed uses 0.17.1 like Lighttable - see the attached screenshot. I don't know why command prompt still runs the 0.17 version - where can it comes from?
![elm_repl](https://cloud.githubusercontent.com/assets/8532967/16539502/613f340e-4045-11e6-9daf-04339480bfc3.jpg)

**Comment by jvoigtlaender** [comment]
In the command prompt, run "where elm-repl" and it should tell you where it comes from.

**Comment by dusky3** [comment]
I mean I know where it is located, but why it is on the PATH when I can't see it. Anyway what is even stranger, I tried it and now I have elm repl 0.17.1 also in the command prompt - see the screenshot. That's why I use windows only at work - it is a crazy unpredictable system. In linux everything  works fine for me (elm as well).

![elm_repl1](https://cloud.githubusercontent.com/assets/8532967/16539822/e796a5ce-404e-11e6-91be-06904b19a107.jpg)

**Comment by jvoigtlaender** [comment]
You didn't do what I asked you to. I asked you to do "where elm-repl", not "where elm". You cannot derive good information from bad experiment.

**Comment by jvoigtlaender** [comment]
And apparently you re-started the command prompt in between, right? Note that any PATH settings will only take effect in a new command prompt after change.

**Comment by jvoigtlaender** [comment]
If you really still want to know where 0.17 came from, you could do:
* temporarily remove the 0.17.1 entry from the PATH
* start a new command prompt
* run "where elm-repl"
* check the result (and probably observe that you installed Elm 0.17 from source at some point, so the elm-repl you get lives in some forgotten `.cabal-sandbox/bin` directory or such)

**Comment by dusky3** [comment]
Thank you @jvoigtlaender. Just to let you know that I restarted the command prompt at least 5 times, but it only changed after typing `where elm`.
