### ISSUE TITLE
tough-cookie@2.2.2 deprecated due to ReDOS vulnerability

### ISSUE THREAD

**Issue by louy2** [elm-lang/elm-platform#167]
Received this npm warning today installing Elm.

    npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie 

Reference: https://nodesecurity.io/advisories/130

tough-cookie@2.2.2 is depended on by request@2.72.0, which is now updated to 2.74.0, depending on tough-cookie@2.3.1.

**Comment by jvoigtlaender** [comment]
This seems already covered by https://github.com/elm-lang/elm-platform/pull/166, so I don't think an additional open issue is needed?

**Comment by louy2** [comment]
Ah, beaten by 2 days. Strange that I didn't get it from search.
