### ISSUE TITLE
stop trying to make fetch happen

### ISSUE THREAD

**Issue by gilesbowkett** [elm-lang/elm-platform#168]
so once upon a time there was a GitHub outage, and during that GitHub outage, somebody tweeted that they couldn't use the Elm REPL:

https://twitter.com/spicy_sake/status/789219031555407873

So this happened because the Elm REPL loads packages lazily via `elm-package`, and inside `elm-package`, there's this `Fetch` module at `src/Install/Fetch.hs`. This `Fetch` module contains a `fetch` function, which uses `ifNotExists` to determine if it has a particular package on the filesystem. If it doesn't, it tries to make `fetch` happen.

However, if GitHub is down, or if your WiFi is down, or there are similar, it can't make `fetch` happen, it's never going to happen.

Therefore, it would be awesome to prefetch `elm-lang/core` so that the Elm REPL can run the core language even when GitHub is down.

(It's not actually a very common problem, I think, because the first thing I did when I saw this tweet was turn off my WiFi and attempt `1 + 2` in the Elm REPL, and it worked just fine, because I had already used the core language with the REPL before, so the package was already downloaded. Probably, anybody who downloads the REPL *and then uses it* will also be able to use it in the event of a GitHub outage. But it is a pretty silly fail state.)

**Comment by reinh** [comment]
![](http://i3.kym-cdn.com/photos/images/original/000/768/910/412.png)

**Comment by eeue56** [comment]
This is a duplicated issue of https://github.com/elm-lang/elm-repl/issues/54 and should be closed.

**Comment by reinh** [comment]
@eeue56 Are you a maintainer of this repository? I just want to know if your response is representative of the community here.

**Comment by JoeyEremondi** [comment]
Any proposed changes to this need to provide an elegant solution for how to deal with multiple versions of libraries, which is why it does the per-package download in the first place.

**Comment by reinh** [comment]
@JoeyEremondi With Haskell, the version of 'base' is tied to the version of GHC. Is this not the case with Elm? That is, is it possible to have multiple conflicting versions of the core library?

**Comment by eeue56** [comment]
As this issue will be closed anyway, @reinh please read this https://github.com/process-bot/contribution-checklist/blob/master/participation.md 

These are the rules for participation and contributions to all elm-lang repos.

> Issues and pull requests are treated more like a work queue than a discussion platform
> It is usually better to talk through stuff in a community forum and summarize it down into a clear idea before it becomes an issue.

**Comment by reinh** [comment]
@eeue56 GitHub provides [a mechanism](https://github.com/blog/1184-contributing-guidelines) for specifying contribution guidelines, which this repository does not use. I'm not sure how I or any other potential contributor is supposed to know to find these guidelines in an entirely separate, unrelated repository that is never mentioned by this repository's documentation.

I find your responses dismissive and unhelpful and I would like to know if you represent this (or any Elm) project in an official capacity.

**Comment by eeue56** [comment]
@reinh 

>  GitHub provides a mechanism for specifying contribution guidelines, which this repository does not use. I'm not sure how I or any other potential contributor is supposed to know to find these guidelines in an entirely separate, unrelated repository that is not mentioned by this repository's documentation.

Community contributions are hard and involve people. Elm-platform does not have the process bot as the other repos do, yet. I assume it probably will soon. See an example here -> https://github.com/elm-lang/core/issues/731#issuecomment-253663902 

> I find your responses dismissive and unhelpful and I would like to know if you represent this (or any Elm) project in an official capacity.

I'm sorry you find them unhelpful. My response was to help those who will fix the issue, rather than the issue creator :) As you can see from the other issue, it has been brought up and discussed many times before. That is the reasoning behind this issue being closed - it is known to be a problem and a duplicate issue. It's great that is was reported again however! I do not represent Elm in any official capacity other than being one of the biggest community contributors.

**Comment by gilesbowkett** [comment]
Hey, I closed the issue, and sorry I missed the thing about preferring to bring it up in the community first. I knew the "fetch" thing was kind of silly but didn't mean any harm.

I should have checked elm-repl for the issue, but after tracking it through the repl and elm-package, it seemed as if the solution was an installer change, so I came here instead.

**Comment by eeue56** [comment]
@gilesbowkett to make it clear I wasn't calling you out on anything! I was just trying to make it easier to keep track of these duplicated issues. The linked issue is an old one that would've been tricky to find, and I only knew about it because I made it! So don't worry about it at all. It's great that you made this issue in the first place and took a little search into what's going on behind the scenes.

**Comment by gilesbowkett** [comment]
@eeue56 to be fair, @reinh helped me dig into the Haskell. his contribution was more than just the meme. :-) and actually I think I'd seen that "no memes" thing before I asked for his help in the first place, and then just forgot about it. so maybe I should have remembered and warned him.

anyway, just wanted to help. I've been telling people "try Elm, try Elm!" and that tweet kind of annoyed me. in fact when I saw it I went to elm-repl to file an issue, but I saw 36 issues and one pull request, so I decided to see if I could make a PR first instead.

**Comment by reinh** [comment]
> I was just trying to make it easier to keep track of these duplicated issues. The linked issue is an old one that would've been tricky to find, and I only knew about it because I made it! So don't worry about it at all. It's great that you made this issue in the first place and took a little search into what's going on behind the scenes.

This is the kind of thing that takes a marginal amount of additional effort but really improves the feeling that contributors get even from failed attempts that end up getting closed. And again, GitHub provides a mechanism to inform contributors of your guidelines. If I had been able to read those guidelines, I could have adapted my behavior appropriately. Instead, I was scolded for not following rules I couldn't have reasonably been expected to know about in the first place, what was not pleasant.

**Comment by eeue56** [comment]
Gotcha. Well, like I said, community contributions involve people, and people make mistakes. I should've used a softer tone, perhaps, and linked to the process-bot documentation to make it clearer.

It's all about making Elm the best thing possible, and one of the sadly tricky bits of that is managing issues in a productive manner, which can sometimes lose the human touch. The Elm Slack channels are a great place for more "free" discussions.

@evancz, process-bot should probably be enabled on this repo, right?

**Comment by gilesbowkett** [comment]
+1 both for process-bot being enabled, and for setting up standard GitHub [contributing guidelines](https://github.com/blog/1184-contributing-guidelines).
