### ISSUE TITLE
0.18 upgrade/migration guide doesn't mention anything about Task.andMap

### ISSUE THREAD

**Issue by jamesmacaulay** [elm-lang/elm-platform#169]
https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.18.md

I was curious about `Task.andMap` because it was one of the functions that typically relied on the soon-dead backticks. It's missing in core's dev branch as of [this commit](https://github.com/elm-lang/core/commit/a8ea710aa36c5223c9e150c2ee159ebe5b07b3fa), but I'm not sure if the intention was to put it back in a different form.

Whether it's really gone or will just be changed, the upgrade guide should make note of it.

**Comment by evancz** [comment]
I think it's too late now. Sorry to anyone who stumbled over this!
