### ISSUE TITLE
New thoughts on a Mac PKG installer

### ISSUE THREAD

**Issue by JasonJAyalaP** [elm-lang/elm-platform#17]
Hey Evan. I did the original mac pkg installer, but fell out of touch.

Since then, I've studied the pkg installers (and package management in general on the Mac) and I see a new common practice for programming language installers. Instead of using the Unix FHS and hardcoding paths:

- All directories go into /usr/local/language-name
- No hardcoded paths (bin/binary looks for "../etc/config")
- $PATH is updated by /etc/paths.d/ (a text file called language-name, no extension, with the line /usr/local/language/bin

Additionally, I've created my own system of symlinking with provides multiple versions. Off the top of my head:
- Language-0.1.1 installer installs to /usr/local/language/0.1.1
- All binaries are ln -sf to /usr/local/language/bin/
- All binaries are ln -sf to /usr/local/language/bin as binary-0.1.1

For example, here's the Nimrod postinstall.sh I made:
````bash
#!/usr/bin/env bash

NIMROD_DIR=/usr/local/nimrod
VERSION=0.9.4

mkdir -p $NIMROD_DIR/bin
ln -sf $NIMROD_DIR/$VERSION/bin/nimrod  $NIMROD_DIR/bin/nimrod-$VERSION
ln -sf $NIMROD_DIR/$VERSION/bin/nimgrep $NIMROD_DIR/bin/nimgrep-$VERSION
ln -sf $NIMROD_DIR/$VERSION/bin/babel   $NIMROD_DIR/bin/babel-$VERSION
ln -sf $NIMROD_DIR/$VERSION/bin/c2nim   $NIMROD_DIR/bin/c2nim-$VERSION

ln -sf $NIMROD_DIR/$VERSION/bin/babel   $NIMROD_DIR/bin/babel
ln -sf $NIMROD_DIR/$VERSION/bin/c2nim   $NIMROD_DIR/bin/c2nim
ln -sf $NIMROD_DIR/$VERSION/bin/nimrod  $NIMROD_DIR/bin/nimrod
ln -sf $NIMROD_DIR/$VERSION/bin/nimgrep $NIMROD_DIR/bin/nimgrep
````
This lets multiple version co-exist, all in $PATH, with the last installed version having the shorter, "unqualified" executable name.

Finally, the package installer can offer a sub-package (placed before the "Install 0.1.1" package, unchecked by default) that runs an uninstall script (rm -rf /usr/local/bin/language; rm /etc/paths.d/language):

[ ] Uninstall All Version
[x] Install Language 1.0.2

**Comment by evancz** [comment]
Let's open a new issue to sort out anything that still needs sorting.

**Comment by evancz** [comment]
Oh, I just read through everything. I don't really know if this should be open or closed.

Everything you describe here makes sense to me, but I definitely don't have bandwidth to work on this myself. All the resources that are part of the mac installer are created by hand in some way or another. Whenever there's a change needed, I do it by hand.

**Comment by evancz** [comment]
Alright, I gotta close. Not sure what the correct path forward is, and it's better to close issues when that's the case.
