### ISSUE TITLE
Building from source 0.17 changeWorkingDirectory: does not exist

### ISSUE THREAD

**Issue by insdami** [elm-lang/elm-platform#171]
I'm trying to install elm on Mint.
I've tried using npm but not luck there, it gets stuck running postinstall scripts throwing a timeout at the end. 

I've made some progress running from the source but I'm getting this error:
BuildFromSource.hs: elm-compiler: changeWorkingDirectory: does not exist (No such file or directory)

This is my env at the moment:

```
elm> cat /etc/linuxmint/info
RELEASE=17.1
CODENAME=rebecca
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 17.1 Rebecca"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_rebecca_cinnamon_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_rebecca_cinnamon.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 17.1 Cinnamon 64-bit

elm> ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3

elm> cabal --version
cabal-install version 1.22.6.0

elm> more ~/.bashrc | grep -1 elm

export ELM_PLATFORM=$HOME/dev/sdk/elm/Elm-Platform/0.17/.cabal-sandbox/bin
export PATH=$PATH:$ELM_PLATFORM
```

Output when the script is run

```
elm> runhaskell BuildFromSource.hs 0.17
Using GHC 7.10
Using Cabal 1.22.6.0

Cloning into 'elm-compiler'...
remote: Counting objects: 24145, done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 24145 (delta 19), reused 0 (delta 0), pack-reused 24103
error: RPC failed; result=56, HTTP code = 200
Receiving objects: 100% (24145/24145), 6.40 MiB | 276.00 KiB/s, done.
Resolving deltas: 100% (14814/14814), done.
BuildFromSource.hs: elm-compiler: changeWorkingDirectory: does not exist (No such file or directory)
```

**Comment by jvoigtlaender** [comment]
The problem clearly seems to be what is signaled by this line in your screen content:
```
error: RPC failed; result=56, HTTP code = 200
```
That comes from `git`, not from the install script. It seems that somehow the `git clone https://github.com/elm-lang/elm-compiler.git` did not work, or at least not completely (despite the "100%" messages)?

Could be an issue with your network connection or setup. See http://stackoverflow.com/questions/26197171/git-clone-repository-error-rpc-failed-result-56-http-code-200.

**Comment by insdami** [comment]
Thanks,

I changed line **208** on BuildFromSource.hs to use [ssh](https://confluence.atlassian.com/bitbucket/set-up-ssh-for-git-728138079.html) 

replaced this `git [ "clone", "git@github.com:elm-lang/" ++ projectName ++ ".git" ]` for `git [ "clone", "git@github.com:elm-lang/" ++ projectName ++ ".git" ]`

And now works :+1: 

```
elm repl
---- elm repl 0.17.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> 
```
