### ISSUE TITLE
Using an incorrect dependency version results in misleading error message

### ISSUE THREAD

**Issue by tilmans** [elm-lang/elm-platform#172]
I've configured a dependency to elm-community/elm-webgl with an incorrect version. The newest version currently is 3.0.3: 

    "elm-community/elm-webgl": "4.0.0 <= v <= 5.0.0",

This results in `elm package install` giving me the following 2 incorrect cases:

* If elm-stuff does not exist yet:  
Results in error: `elm-package: elm-stuff/exact-dependencies.json: openBinaryFile: does not exist (No such file or directory)`

* If elm stuff does exist:   
Tells me some new packages are needed, when I approve it appears to install something but `elm-stuff/packages/elm-community/elm-webgl` will be empty.

**Comment by jvoigtlaender** [comment]
This belongs in https://github.com/elm-lang/elm-package/issues, and almost certainly there is already an issue open about it over there.

Please check, and close here.

**Comment by tilmans** [comment]
Duplicates https://github.com/elm-lang/elm-package/issues/250
