### ISSUE TITLE
suggest adding "build from source on  FreeBSD" update to readme.md  

### ISSUE THREAD

**Issue by oschonrock** [elm-lang/elm-platform#174]
npm is a mess. I hate it. the whole concept of installing all of node just so you can use the package manager is seriously flawed? Anyway that why we use elm right ;-) get rid of JS!

This is not a bug, just notes. Actually got quite far in about 10mins. Apart from one small issue, see below.

All I did was:
```
# as root
pkg install ghc hs-cabal-install
# as normal user (unless you want to install in /usr/local/)
WORK_DIR=~/elm  # change as required
mkdir "$WORK_DIR/Elm-Platform/0.17/"
PATH="$PATH:$WORK_DIR/Elm-Platform/0.17/.cabal-sandbox/bin"
curl https://raw.githubusercontent.com/elm-lang/elm-platform/master/installers/BuildFromSource.hs > BuildFromSource.hs
runhaskell BuildFromSource.hs 0.17
```
the small issue was this:
https://github.com/snapframework/snap-server/issues/91
there is a commit that fixes it, just need to figure out how to patch that in 
will come back with solution soon I hope...

**Comment by evancz** [comment]
I do not think we can maintain full instructions for every platform that wants to build from source in this repo. It sounds like the suggestion here did not work. I'm not sure how to proceed, so I will close.
