### ISSUE TITLE
Elm installation error (from npm)

### ISSUE THREAD

**Issue by recurza** [elm-lang/elm-platform#175]
This is the error I got after doing `npm i -g elm` :
```
Downloading Elm binaries from https://dl.bintray.com/elmlang/elm-platform/0.17.1/linux-x64.tar.gz
Error decompressing linux-x64.tar.gz Error: unexpected end of file
```
Node 7.0.0, npm 3.10.9, Arch Linux on VirtualBox.

(edit: Attached [npm-debug.log.txt](https://github.com/elm-lang/elm-platform/files/580076/npm-debug.log.txt))

**Comment by evancz** [comment]
Sorry you ran into this! @rtfeldman may know more about this, but I'd recommend asking around on http://elmlang.herokuapp.com/ to get more feedback. It kind of seems like the connection just got cut off though. Not enough bits were transferred to you. I wonder if you get the same message on retry?

**Comment by recurza** [comment]
Yes,  I also tried npm@lts and wiped the cache, but no luck.
Strange thing is, there are no problems if I wget the url and uncompress it
manually.​ Also,
​ ​
I'm able to install it on the Windows 10 bash.
​​

​​
Sure, I'll go on Slack and ask there.
​ If it's not a common case, I can always build elm manually.​

**Comment by evancz** [comment]
Also, I wonder if there's something weird going on where your VM thinks it is 64-bit but it's not for some reason. I can't really think of anything else that might be causing this.

**Comment by recurza** [comment]
I tried npm installing again today and it *worked??* Very very weird. I'm going to close this issue - if anyone else sees this, the solution is to wait idly a few days :+1:

**Comment by stil4m** [comment]
For the sake of recording: We encountered this on our internal CI environment a few times in the last few days. After retries, it seems to work.
