### ISSUE TITLE
Should mention some alternative for Maybe.oneOf

### ISSUE THREAD

**Issue by SLOBYYYY** [elm-lang/elm-platform#182]
I added a PR to update the docs to mention the removal in the first place.

Although the function itself is not a complicated one, the migration docs should mention something about replacing it with something else.

Also, why was it removed in the first place?

**Comment by evancz** [comment]
A few notes on this in https://github.com/elm-lang/core/commit/5f43ad84532bd4d462edf5c1ec22b7a62352a2db

We had quite a long alpha and beta period before 0.18 was released and no compelling examples were brought forward. Perhaps people were using it in a good way, but I cannot think of an example of that and have not heard of one.
