### ISSUE TITLE
Platform.program doesn't work

### ISSUE THREAD

**Issue by Pilatch** [elm-lang/elm-platform#187]
I have a Main port module that uses Platform.program. It will compile index.html just fine. However when I load it up in the browser and this is what we get:

    index.html:3175 Uncaught ReferenceError: _elm_lang$core$Json_Decode$andThen is not defined(…)(anonymous function) @ index.html:3175(anonymous function) @ index.html:3259
index.html:3260
    Uncaught ReferenceError: Elm is not defined(…)(anonymous function) @ index.html:3260

elm-make -v
elm-make 0.18 (Elm Platform 0.18.0)

**Comment by Pilatch** [comment]
Here is what Main.elm looks like:

    port module Main exposing (..)

    import Mangle exposing (mangle)


    port input : (MangleData -> msg) -> Sub msg


    port output : String -> Cmd msg


    type alias MangleData =
        { mangleOffset : Int, stringToMangle : String }


    type Msg
        = MangleRequestedOn MangleData

    initialModel : MangleData
    initialModel =
        MangleData 0 ""


    update : Msg -> MangleData -> ( MangleData, Cmd Msg )
    update msg data =
                let
                    mangledString =
                        mangle data.mangleOffset data.stringToMangle
                    newModel = MangleData (data.mangleOffset + 1) ""
                in
                    (newModel , output mangledString)

    publish : Msg -> Cmd Msg
    publish msg =
        case msg of
            MangleRequestedOn data ->
                let
                    mangledString =
                        mangle data.mangleOffset data.stringToMangle
                in
                    output mangledString




    subscriptions : MangleData -> Sub Msg
    subscriptions mangleData =
        input MangleRequestedOn

    main : Program Never MangleData Msg
    main =
        Platform.program {
            init = (initialModel, Cmd.none),
            update = update,
            subscriptions = subscriptions
        }

... and Mangle.elm ...

    module Mangle exposing (..)

    import Char
    import List
    import String


    mangleChar : Int -> Char -> Char
    mangleChar offset char =
        char
            |> Char.toCode
            |> (+) offset
            |> Char.fromCode


    mangle : Int -> String -> String
    mangle offset str =
        let
            mangleCharWithOffset =
                mangleChar offset
        in
            str
                |> String.toList
                |> List.foldl (\char charList -> mangleCharWithOffset char :: charList) []
                |> String.fromList

... and the pertinent part of elm-package.json ...

    "dependencies": {
        "elm-lang/core": "5.0.0 <= v < 6.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"

**Comment by xarvh-at-stax** [comment]
It is a known issue https://github.com/elm-lang/elm-make/issues/127
