### ISSUE TITLE
npm install -g elm

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-platform#19]
I don't think this has been captured in an issue yet, but the title says it all!

JS developers would definitely appreciate if the instructions for getting Elm could be as simple as running `npm install -g elm` - like [CoffeeScript does on its homepage](http://coffeescript.org/).

**Comment by passy** [comment]
Kevin did some awesome work and it's now possible to install elm with just

`npm install --global elm-platform-bin`

on x64 Linux and OS X. The binaries live in the repository itself at the moment, but I guess it would be preferable to host them somewhere else. @evancz How do you currently prefer the binary bundles for the various platforms?

**Comment by evancz** [comment]
I don't know the answers to these questions better than you. I am in Budapest now, so it should be easy to do a quick call to sort out any long term planning details as I am struggling in this format.

As I said before, I am excited to host stuff at `whatever.elm-lang.org` which is backed by a CDN (where `whatever` is whatever you want it to be). If I get a tarball of things I should host there, I will totally do it and be very happy.

I do not know the details of this project though. I am not a super expert on installers and distributing stuff, so your guess is probably better than mine. I am trying to keep up with a ton of stuff at this point, so the less I know, the happier I will be and the more progress I can make on other stuff. I am happy to fulfill concrete requests and answer planning questions, but I do not know what is being asked of me at this point or how I can help.

**Comment by evancz** [comment]
Sorry, I have had a frustrating morning with some emails, so that is coming out here.

It feels like we should coordinate on how to do releases. Ideally this can be the official install route, because it freakin' rocks. I think we'd benefit from talking face-to-face (through the internet) so I'll start trying to set that up.

**Comment by sonnym** [comment]
I believe this issue can be closed in light of: https://github.com/kevva/elm-platform-bin/issues/4

**Comment by evancz** [comment]
Yep, thanks everyone! :D
