### ISSUE TITLE
NPM install on windows 8 fails

### ISSUE THREAD

**Issue by Neftedollar** [elm-lang/elm-platform#192]
Hi, I've got the same problem as #100, but I haven't managed to resolve it by updating `npm` and `node` to the latest versions.

We have self-signed corporate certificates here which I put in npm `ca`/`cafile` settings, but in vain.
I can open https://dl.bintray.com/elmlang/elm-platform/0.18.0/ in the browser, but npm can't reach the binaries.

Here's the console output:
```
npm i elm
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN prefer global elm@0.18.0 should be installed with -g

> elm@0.18.0 install C:\Users\<...>\node_modules\elm
> node install.js

Error communicating with URL https://dl.bintray.com/elmlang/elm-platform/0.18.0/win32-x64.tar.gz Error: self signed certificate in certificate chain
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\<...>\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "elm"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! elm@0.18.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elm@0.18.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the elm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs elm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls elm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\<...>\npm-debug.log
```

**Comment by kasrasadeghi** [comment]
Your problem looks like the same as mine.

**Comment by nojaf** [comment]
Having the same problem, also behind a corporate proxy.

**Comment by muellerk22** [comment]
Me three,  Also, behind a corporate firewall but using Artifatory to proxy to npm.  Can the https://dl.bintray.com/elmlang/elm-platform/0.18.0/linux-x64.tar.gz be place in a location that npm can install directly via npm?

**Comment by jparaya** [comment]
Same problem here, but I have an ETIMEDOUT. `Error: connect ETIMEDOUT xxx.xxx.xxx.xxx443`

If I try to download the tar.gz file via browser, it takes about 3-5 minutes, but finally downloads it. I guess the proxy has to check the content of the file first.

Is there any way to fake the url, to point to a local server, for example? Or by setting a bigger time frame to wait for the response... I tried to change the file install.js, but npm first needs to remove the folder to install it again

**Comment by jparaya** [comment]
Same problem here, but I have an ETIMEDOUT. Error: connect ETIMEDOUT xxx.xxx.xxx.xxx:443

What I did is to download the file from my browser (I can download it, but the download takes about 3-5 mins. I guess the proxy takes its time to validate the content). Then when npm executes `node install.js` I simply stop the process and modify the `install.js` file to point to a local web server where I host the file. That's it.

I can run elm apps, but in order to install packages, I need to set the proxy env on the console (I thought I will be able to take the configuration from .nprmc)

```
set http_proxy=http://proxy:port/
set https_proxy=http://proxy:port/
```

**Comment by evancz** [comment]
It's not clear to me what should change in this repo based on what you are saying. I have opened #223 to summarize the problem, outline a solution, and solicit feedback in a specific way.
