### ISSUE TITLE
Restore [a..b] list range syntax in Elm language definition

### ISSUE THREAD

**Issue by benjamin-rood** [elm-lang/elm-platform#201]
Quote from 1.8 release:

>List Ranges
>
>The [1..5] syntax has been removed.
>
>So replace any occurance of [1..9] with List.range 1 9.

`List.range` is requires more typing and is more typo-prone given the mix of cases. Considering the limited number of code editors which have Elm syntax snippet packages this is doubly annoying.

`[a..b]` is a tried and tested approach which has worked for programmers for decades.

Please can we restore the classical range syntax to Elm? Or potentially, if it was producing significant compiler/lexer problems, settle for `[a .. b]` or `[a...b]`?

**Comment by evancz** [comment]
Like @process-bot says, I prefer to use issues are for tracking bugs. If you start revisiting choices and doing design discussion in this medium, it gets out of control. That said, I do not plan to flip-flop on that decision. Sorry if this message sounds curt.
