### ISSUE TITLE
Incremental compilation

### ISSUE THREAD

**Issue by eirslett** [elm-lang/elm-platform#202]
How can you do incremental changes to the compiler, and then do a quick incremental compilation of the compiler and elm-make, to do a test compile on a project?
`runhaskell BuildFromSource.hs master` works, but it takes ~1 minute 30 seconds on my machine, which is a bit long.

**Comment by evancz** [comment]
It's just slow. I think this is a combination of the compiler being complicated and the length of Haskell compile times. Not sure how to make your case nicer.
