### ISSUE TITLE
BuildFromSource.hs: uses all cores by default

### ISSUE THREAD

**Issue by amigalemming** [elm-lang/elm-platform#204]
BuildFromSource.hs calls 'cabal -j' and thus uses all cores. I have virtually 8 cores but actually only 4 ones, each with two hyperthreads. That is, my machine is in no way able to achieve a speedup of factor 8. What it actually does is to drive my harddisk crazy and makes the machine unresponsive. I think it is generally a very very very bad idea to use more than one core by default. The simplest thing would be to omit the '-j' option completely and rely on the user to set an appropriate option in his cabal-config.
Btw. I would prefer to use a standard installation procedure, e.g. installing with Cabal from Hackage. I could add '-j' options as it fits for me or could use a sandbox. What was so bad about releasing the Elm compiler at Hackage? Cabal downloads all the depending packages automatically.

**Comment by amigalemming** [comment]
Maybe #200 would just solve this problem, too.

**Comment by evancz** [comment]
Haskell seems to have trouble with high numbers of cores in general. The goal is to make builds easy for creating installers, so the settings are optimized for that scenario. Sorry for the trouble.
