### ISSUE TITLE
npm installer should work with --ignore-scripts

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-platform#205]
If you run `npm install --ignore-scripts`, the npm installers should still work.

This is possible if the default binaries change. Currently they pretty much echo "uh oh something went wrong!" because they were supposed to get overwritten by the downloaded ones.

What they can do instead is to attempt to download the actual binaries, install them, and then run them. This way, even if the post-install scripts didn't run, you will still "lazily" get the outcome you wanted. It's just that the first time you run `elm-make` it will be a tiny script that downloads the Elm Platform, installs it over the `elm-make` you ran, and then runs the real `elm-make`.

Running the `elm-make` script may mean that it's not possible to copy a new `elm-make` over the original while it's still running. If that's true, though, there may also be a way to do some careful process management to get around that. I'm not sure.

**Comment by evancz** [comment]
Let's make a meta issue of anything you want to do with the `npm` installer.
