### ISSUE TITLE
Release linux binaries outside of NPM.

### ISSUE THREAD

**Issue by MicahZoltu** [elm-lang/elm-platform#207]
I'm trying to build a docker image with elm and I don't want to have to install NPM just so I can install Elm.  Is there some technical reason why the Linux binaries aren't released outside of NPM?

**Comment by lydell** [comment]
@MicahZoltu I guess you can download binaries from the same [URL as the npm installer does](https://github.com/elm-lang/elm-platform/blob/56dce575aea13a6e09c304ff6208183fcc7839d0/installers/npm/install.js#L34-L42).

**Comment by evancz** [comment]
The original suggestion is pretty vague, and it seems like @lydell's suggestion covers the stated problem. If there are specific things you are requesting, please open a new and more specific issue.

**Comment by MicahZoltu** [comment]
I'm not using elm at the moment, so probably won't create a new issue.  However, it would be nice if those download links were publicly documented.  I shouldn't have to dig through package management source code to find download links.
