### ISSUE TITLE
Building elm-repl requires ncurses dependency.

### ISSUE THREAD

**Issue by rudi-c** [elm-lang/elm-platform#21]
This is not included by default on Ubuntu distros, and the dependency check appears relatively late during the build making the error hard to spot.

**Comment by conklech** [comment]
I resolved this problem by installing the `libtinfo-dev` package on Ubuntu.

I also needed to install `zlib1g-dev`. (This happens to be a very new install; I'd expect most experienced developers would already have that installed.) 

Could we update the Linux installation documentation to mention these dependencies?

**Comment by evancz** [comment]
Yes. I don't know where to add that but I'll happily accept a PR to alleviate this!
