### ISSUE TITLE
npm installation support for binaries mirror

### ISSUE THREAD

**Issue by thiagofigueiro** [elm-lang/elm-platform#211]
The [npm installer hard-codes the download URL](https://github.com/elm-lang/elm-platform/blob/master/installers/npm/install.js#L41) to `https://dl.bintray.com/elmlang/elm-platform/`:

```javascript
    var filename = operatingSystem + "-" + arch + ".tar.gz";
    var url = "https://dl.bintray.com/elmlang/elm-platform/"
      + platform.elmVersion + "/" + filename;
```

In some environments it's not possible to access external URLs and all dependencies must be fetched from a local mirror.

The only work-around that I can think of is to "hijack" the dl.bintray.com hostname (e.g. via a hosts file entry) and replicate the content structure.  I don't know what would be needed to work-around the x509 certificate and I haven't tried it.

It would be most useful if there was a way to specify a mirror for the elmlang binaries during installation.

**Comment by Kevin-Lee** [comment]
This is a problem for me too. 😔

**Comment by evancz** [comment]
This is for the `npm` install path correct?

Why not host the executables on your infrastructure and just download them from there? Seems way easier than mirrors or hijacking or anything. Make a `download-elm.sh` and call it when you need to.

If this is unworkable, please discuss with known community members on Slack, and after refining it, open a new issue explaining the particulars that'd make `download-elm.sh` not ideal.
