### ISSUE TITLE
Will BuildFromSource.hs be compatible with ghc 8.0?

### ISSUE THREAD

**Issue by reinaldorauch** [elm-lang/elm-platform#214]
Tried to run the script with ghc 8.0 and received the message:

```
You need GHC 7.10 to build this version of Elm.
You are using GHC 8.0 instead.
```

Can I modify the script to run with 8.0 or there is compat issues with it?

Thanks for your attention.

Edit:

Using
Linux Distro: Manjaro Gellivara 17.0.2
Kernel Linux reinaldo-note-manjaro 4.9.39-1-MANJARO #1 SMP PREEMPT Fri Jul 21 08:25:24 UTC 2017 x86_64 GNU/Linux
Haskell Platform Version: 8.0 from AUR repository

**Comment by jvoigtlaender** [comment]
There are dependencies that currently prevent building with GHC 8. So the warning is there to prevent you from trying something that would fail anyway.

**Comment by evancz** [comment]
Yeah, the compiler is built with 7.10 still. If newer versions of Elm are built with newer versions of GHC, that will be reflected in the build script.

**Comment by reinaldorauch** [comment]
Thanks :D
