### ISSUE TITLE
ubuntu 16.04, node v8.5.0,npm 5.4.1 

### ISSUE THREAD

**Issue by mihongkun** [elm-lang/elm-platform#218]
$ sudo npm install -g elm
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/bin/elm -> /usr/lib/node_modules/elm/binwrappers/elm
/usr/bin/elm-make -> /usr/lib/node_modules/elm/binwrappers/elm-make
/usr/bin/elm-package -> /usr/lib/node_modules/elm/binwrappers/elm-package
/usr/bin/elm-reactor -> /usr/lib/node_modules/elm/binwrappers/elm-reactor
/usr/bin/elm-repl -> /usr/lib/node_modules/elm/binwrappers/elm-repl

> elm@0.18.0 install /usr/lib/node_modules/elm
> node install.js

Error extracting linux-x64.tar.gz - Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/elm/Elm-Platform'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm@0.18.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elm@0.18.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/m/.npm/_logs/2017-09-14T08_43_28_874Z-debug.log

**Comment by mihongkun** [comment]
[Solution by this](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md#install-npm-packages-globally-without-sudo-on-macos-and-linux)

**Comment by tino415** [comment]
I had same problem, but solved it by running `sudo npm install -g elm --unsafe-perm=true --allow-root` from [this issue in electron](https://github.com/npm/npm/issues/18373)

ubuntu 16.04
node -v  v7.10.0
npm -v 5.3.0

**Comment by titomarifrancis** [comment]
I also encountered this issue recently. The problem I think is that the default installation of NodeJS in Ubuntu 16.04 installs "nodejs" rather than "node", to resolve this, run this command on CLI:

sudo ln -sf /usr/bin/nodejs /usr/bin/node

After this, try to install elm as usual. Hope this helps :)

**Comment by Chilinot** [comment]
Confirming the issue on my system as well:
Fedora release 27 (Twenty Seven)
Node v8.9.3
npm 5.5.1

@tino415's solution worked for me

**Comment by palutz** [comment]
Same problem here:
Ubuntu 17.04
node v 8.9.4
npm v 5.3.0

**Comment by DanielSokil** [comment]
@tino415 Thanks! 
`sudo npm install -g elm --unsafe-perm=true --allow-root`
Worked for me.

**Comment by rtfeldman** [comment]
OP's issue has been resolved: https://github.com/elm-lang/elm-platform/issues/218#issuecomment-329420591
