### ISSUE TITLE
Unable to run elm-make from project directory on macOS

### ISSUE THREAD

**Issue by wittjosiah** [elm-lang/elm-platform#219]
We have a [Spring Framework](https://spring.io/) project that currently has a React frontend. I am working on introducing Elm into this project. The project uses [this neat maven plugin](https://github.com/eirslett/frontend-maven-plugin) to install node/npm/webpack and build the frontend all in the project directory automatically. The primary purpose of this is to allow developers working on the backend not to have to setup a frontend development environment. Since I am able to install Elm via npm I figured it would be possible to set it up so that Elm is installed in the same fashion. This has turned out to be partially true, though I have run into some issues.

Looking at the [node-elm-compiler](https://github.com/rtfeldman/node-elm-compiler) and the [elm-webpack-loader](https://github.com/elm-community/elm-webpack-loader) I was able to find the `pathToMake` option, which allowed me specify that it should use the local elm in `node_modules`. This worked...kinda. It did indeed try to compile using the local version rather than the global version however, unlike the globally installed version the binaries do not seem to be executable on macOS. I get the error `Module build failed: Error: Compiler process exited with error Compilation failed...node_modules/elm/Elm-Platform/0.18.0/.cabal-sandbox/bin/elm-make: cannot execute binary file`. Looking at the file it seems it is compiled for Linux systems:
```
$ file elm
elm: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=91fa5dc5d7f1c921af43cc236a34aaa3b371a777, stripped
```
And indeed, I was able to run the binary in the `node` docker image. Hopping into the docker image I did the following:
1. Recreated the node-elm-compiler [HelloWorld example](https://github.com/rtfeldman/node-elm-compiler/blob/master/examples/HelloWorld.elm)
1. Ran `npm install elm node-elm-compiler`
1. In the `node` REPL ran
```
var elmCompiler = require('node-elm-compiler');
elmCompiler.compileToString(["./HelloWorld.elm"], { yes: true, output: "index.html", pathToMake: "./node_modules/elm/binwrappers/elm-make" }).then(function(data){
    console.log("Text", data.toString());
});
```
This succeeded, and when I exited the REPL I was able to run the binary ./node_modules/elm/Elm-Platform/0.18.0/.cabal-sandbox/bin/elm properly.

Is there a reason why when I run `npm install -g elm` and `npm install elm` I seemingly get different binaries? Is there a way to get platform specific binaries when not running with `-g`?

**Comment by zwilias** [comment]
The install-script uses [`process.platform`](https://github.com/elm-lang/elm-platform/blob/master/installers/npm/install.js#L13) to figure out what platform you're on. So either someone accidentally ran `npm i elm` from within some container, or `npm` (when triggered through Eirik's maven plugin) mistakenly thinks it's running on linux.

Long story short: the installer believes whatever node claims the current platform is, independent of project-local or global installation.

**Comment by wittjosiah** [comment]
@zwilias Thanks for responding to this so quickly, that's helpful information. I will check it out and see if I can track down the issue.

**Comment by wittjosiah** [comment]
@zwilias As far as I can tell you're right about that being the issue. After removing node_modules and package-lock.json and reinstalling it seems to be working. Thanks!
