### ISSUE TITLE
npm run dev 无法运行，build 可以。

### ISSUE THREAD

**Issue by SunnyTuZi** [elm-lang/elm-platform#220]
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! elm@2.0.1 dev: `cross-env NODE_ENV=online node build/dev-server.js`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the elm@2.0.1 dev script 'cross-env NODE_ENV=online node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the elm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=online node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs elm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls elm
npm ERR! There is likely additional logging output above.

**Comment by zwilias** [comment]
@SunnyTuZi can you try installing `elm@0.18.0`? It seems like your npm version doesn't respect the `latest` tag.

**Comment by evancz** [comment]
Not sure how to proceed here. Going to close and ask that people continue on the Slack channel.
