### ISSUE TITLE
Corporate users cannot access dl.bintray.com

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-platform#223]
People in #192 and #211 said that they cannot download from:

    https://dl.bintray.com/elmlang/elm-platform/

If they do not trust that site, I am not sure what external site they would trust by default. So I do not see a clear path on the Elm side. Instead, it seems to make sense to acquire and vet the binaries (probably building from source so you can look through the source code) and serve it on your internal infrastructure.

If this is not correct, please create a separate issue that explains your situation and why this path is inadequate.

**Comment by rtfeldman** [comment]
Closing in favor of https://github.com/elm-lang/elm-platform/issues/224 which should address this.
