### ISSUE TITLE
elm command not found

### ISSUE THREAD

**Issue by suri1313** [elm-lang/elm-platform#230]
Hi there,

  I am using "Linux 3.10.0-514.21.1.el7.x86_64", we have some shell scripts they have included this elm command to send email alerts to some mail users, but today while executing one of the script it is throwing an error that "elm: command not found". Earlier it was working fine, I mean we used to get email alerts when we execute any of the script in the server.  I have tried many commands about this elm service but I couldn't find anything. can somebody please help me on this.

Still need any additional info please let me know.

Regards,
Alex

**Comment by zwilias** [comment]
Hi,

I think you may be talking about [elm, the email client](https://en.wikipedia.org/wiki/Elm_(email_client)) rather than [Elm, the programming language](http://elm-lang.org).

This organisation is for the programming language.

Good luck!
