### ISSUE TITLE
Ship documentation for the standard libraries with elm-platform

### ISSUE THREAD

**Issue by irrwitz** [elm-lang/elm-platform#3]
Hi, 

this is an enhancement request (IMHO). 

I have installed the elm-platform via the windows-installer but the documentation for the standard libraries are not shipped with the installer/platform, or I haven't found them. It would be great if documentation from http://library.elm-lang.org/catalog/evancz-Elm/0.12/ is available for local usage. 

Thx,
Joshy

**Comment by evancz** [comment]
Between https://github.com/elm-lang/elm-plans/issues/20 and https://github.com/elm-lang/elm-make/issues/28 we should have you covered. Not sure the exact timeline on these things, but follow along on those issues to see the progress we make.

Thanks for reporting your issue!
