### ISSUE TITLE
Direct-install from brew?

### ISSUE THREAD

**Issue by jasonkuhrt** [elm-lang/elm-platform#36]
Wouldn't this be good or is there a reason we don't want to support it?

```
⧑ brew install elm-platform

Error: No available formula for elm-platform
Searching formulae...
Searching taps...
Caskroom/cask/elm-platform
```

**Comment by evancz** [comment]
I have no objection, but I'm also not an expert on creating installers for all the different possibilities. Folks have created a way to install through `npm`, so it's certainly doable! Maybe bring it up on [the mailing list](https://groups.google.com/forum/#!forum/elm-discuss) and try to figure out how to make it happen?

**Comment by jasonkuhrt** [comment]
@evancz Sounds good. Is there a "how-to-help-elm" list somewhere that I could just add this too? Its actually not my speciality to readily achieve this either.

**Comment by evancz** [comment]
I have been making a big list of projects [here](https://github.com/elm-lang/projects) so it would be good to add a section on making installers! Can you open a PR there?

**Comment by jasonkuhrt** [comment]
@evancz https://github.com/elm-lang/projects/pull/6 Done!

**Comment by evancz** [comment]
Awesome, thanks again! And if you feel like it's taking too long, don't be afraid to poke the mailing list to try to make it happen.

**Comment by jasonkuhrt** [comment]
@evancz Sounds good. Thanks for your generosity and openness.

**Comment by lagden** [comment]
```
$ brew search elm
Caskroom/cask/elm-platform
```

**Comment by jasonkuhrt** [comment]
@lagden Is that complete `brew` support for `elm`? If so update the related Readme :+1:

**Comment by lagden** [comment]
Yes, but you need install [Homebrew Cask](http://caskroom.io/) first and then...

```
$ brew cask install Caskroom/cask/elm-platform
```

The current formula is:


```ruby
cask :v1 => 'elm-platform' do
  version '0.15.1'
  sha256 '09ad994a33215d954042c5917423eec0e2adbd6015dd6dd9ef571d5d7af9bf2b'

  url "http://install.elm-lang.org/Elm-Platform-#{version}.pkg"
  name 'Elm'
  homepage 'http://www.elm-lang.org'
  license :bsd

  pkg "Elm-Platform-#{version}.pkg"

  uninstall :pkgutil => 'org.elm-lang.*',
            :delete => '/usr/local/share/elm'
end
```

or

via `Node.js` works fine too! `->` https://github.com/kevva/elm-bin

```
