### ISSUE TITLE
Windows Installer writes the wrong "type" of string to PATH

### ISSUE THREAD

**Issue by murrayh** [elm-lang/elm-platform#38]
**See https://github.com/elm-lang/elm-platform/issues/38#issuecomment-134471413 for full description of the root bug.**

I use variables in my local PATH like so:

    BIN=C:\bin
    SCRIPTS=C:\scripts
    ...
    PATH=%BIN%;%SCRIPTS%;C:\SomeFolder\bin

If I open up a cmd window, I see something like:

    C:\Users\murrayh>echo %PATH%
    C:\Windows\system32;...;C:\bin;C:\Scripts;C:\SomeFolder\bin

After installing Elm, I see something like this:

    C:\Users\murrayh>echo %PATH%
    C:\Windows\system32;...;C:\Elm Platform\0.14.1\bin;%BIN%;%SCRIPTS%;C:\SomeFolder\bin

The work around is for me to open up the PATH variable (as in, go to edit it) and then press OK without changing anything. This action expands the variables.

FYI I created an NSIS installer the other month and as far as I can tell there is no robust way to modify the PATH environment :-(. I went with the large string build (http://nsis.sourceforge.net/Special_Builds) and the patched EnvVarUpdate script (http://nsis.sourceforge.net/Environmental_Variables:_append,_prepend,_and_remove_entries), but my app has a very narrow distribution and a different class of user -- incomparable to Elm (the 0.1% of users with PATH.length > 8192 are probably all developers). I don't know of any solutions.

**Comment by evancz** [comment]
We are actually using [this script](https://github.com/elm-lang/elm-platform/blob/master/installers/windows/updatepath.vbs) to change the PATH and avoid the 8192 issue (which folks ran into when we tried it!)

It sounds like your issue comes from whatever vbs magic is happening there. I don't really get the issue you are having, but if you can frame it in terms of "if we change the vbs script like this, we won't do X" then I think we can fix your case.

Are you still having this issue as of 0.15.1?

**Comment by murrayh** [comment]
Yes, the problem still exists as of 0.15.1.

I just did some lunch time googling, and some quick tests looking at regedit before and after the install, and I 99% sure the solution is to change line 7 of that script:

From:
    Call WshShell.RegWrite(PathRegKey, newPath)
To:
    Call WshShell.RegWrite(PathRegKey, newPath, "REG_EXPAND_SZ")

https://msdn.microsoft.com/en-us/subscriptions/yfdfhz1b%28v=vs.84%29.aspx

I actually spent a lot of time (many days) trying to find a solution to this issue some months ago, without luck. You may actually have a PATH solution on your hands here that the NSIS community desperately needs.

I will eventually test the above fix, but it won't be timely because I need to set the project up from scratch. I thought I would post in case you would like a quicker turn around.

**Comment by murrayh** [comment]
Also would need to apply the patch here:
https://github.com/elm-lang/elm-platform/blob/master/installers/windows/removefrompath.vbs

**Comment by evancz** [comment]
Well if that's the case, thank @agazso, he came up with it :)

My main goal here would be to preserve the PATH as much as possible before and after. Are you saying that, as is, the PATH is not preserved? Yes or no to that.

If the PATH is being preserved, please say more about why you want it to not be. It does not seem clear to me that that'd be nice. (I'm not a huge Windows person anymore so I am not totally clear on what is going on just from the `echo` examples from above. Maybe you can show "this entry" becomes "that entry" for me and I'll see the problem better!)

**Comment by murrayh** [comment]
The contents of the PATH variable are updated correctly, but the behavior of the PATH variable changes. I am not going to answer your questions directly because they are off target, but I will try and explain the problem again.



In windows you can use environment variables inside your PATH environment variable. Windows environment variables are referenced using surrounding % characters, so to get the value of the PATH environment variable you need to use %PATH%.

So instead of having something like this:

    PATH=C:\apps\jdk-8u60-windows-x64\bin;C:\apps\apache-ant-1.9.4\bin

I setup my environment variables like so:

    ANT_HOME=C:\apps\apache-ant-1.9.4
    JAVA_HOME=C:\apps\jdk-8u60-windows-x64
    PATH=%JAVA_HOME%\bin;%ANT_HOME%\bin

This means that I when I upgrade my version of Ant, I change the ANT_HOME variable and my PATH is transparently updated as well. My workplace uses locked down Windows workstations, so I am often installing zip distributions of tools and managing my PATH variable manually.

If I copy and paste my PATH environment variable out of the environment variables dialog, it is literally the string "PATH=%JAVA_HOME%\bin;%ANT_HOME%\bin". But when a Windows application reads the value of the PATH variable, they get the string "C:\apps\jdk-8u60-windows-x64\bin;C:\apps\apache-ant-1.9.4\bin". By default windows transparently expands those embedded environment variables -- applications don't even know that I used environment variables in my PATH.

The Elm installer bug:
 
    1. My path is PATH=%JAVA_HOME%\bin;%ANT_HOME%\bin.

    2. When applications read the value of the PATH variable they see "C:\apps\jdk-8u60-windows-x64\bin;C:\apps\apache-ant-1.9.4\bin"

    3. I install Elm 0.15.1

    4. My path is PATH=C:\apps\Elm Platform\0.15.1;%JAVA_HOME%\bin;%ANT_HOME%\bin.

    5. When applications read the value of the PATH variable they see "C:\apps\Elm Platform\0.15.1;%JAVA_HOME%\bin;%ANT_HOME%\bin"

    6. The end result is that the Java and Ant binaries are no longer visible to the application via the PATH variable.

    7. The contents of the PATH variable were updated correctly (not shortened or anything), just that the transparent variable expansion no longer occurs.


My proposed change should fix this problem because:

    1. In Windows, environment variables are stored in the windows registry.

    2. There are user environment variables (visible to only the current logged in user) and system environment variables (visible to all users across the entire machine). Elm updates the user environment variable (which is excellent, because I don't have permissions to change system variables).

    3. User environment variables can be examined in the registry using the Registry Editor under the path \\HKEY_CURRENT_USER\Environment

    4. Before installing Elm, the PATH registry key (which stores the PATH environment variable) is of the type REG_EXPAND_SZ. After installing Elm, the PATH registry key type is REG_SZ.

    5. The change in registry key type is changing the transparent variable expansion behavior that happens in the background.

      6. Opening the "Edit environment variables dialog", and editing the PATH variable (changing it without actually changing it. eg. append a space) changes the registry key type back to REG_EXPAND_SZ. The problem gets fixed at this point.

    7. So I'm pretty confident my proposed solution will fix the problem. Whether or not the solution actually works depends on whether I got the syntax wrong, made a typo, the extra parameter requires admin privileges, newer version of windows etc. So verification before changing master is needed.

**Comment by evancz** [comment]
Ah, thank you for the very thorough break down! This makes way more sense to me now.

So one way to say it is:

> When we write the new PATH, we are writing it with the wrong "type" 

And you can set the "type" that you write with those crazy flags you pointed to.

This makes a ton of sense to me! If you get a chance to try it out, please send a PR! If it happens that you try it out for some other installer you are making, definitely open the PR or let us know. It'd be great to have the viable PR there even if I need to do some final testing before we do our next release.

**Comment by murrayh** [comment]
Yes, that's exactly it, though I did not know that when I opened this ticket (I only knew of the symptoms not the cause). I will try the proposed solution out and send a PR, perhaps sometime next week.
