### ISSUE TITLE
elm-server: Seg fault

### ISSUE THREAD

**Issue by marklar** [elm-lang/elm-platform#4]
Platform: Mac OS X 10.7.5

Installation:
  * first, using the Mac installer
  * second, using cabal

Both times, I encountered this problem when attempting to run `elm-server`:
/usr/local/bin/elm-server: line 6: 85772 Segmentation fault: 11  /usr/local/bin/elm-server-unwrapped $*

**Comment by evancz** [comment]
Alright, elm-sever no longer exists, so I'm gonna close this one!
