### ISSUE TITLE
Cannot build elm-compiler after elm-package was built

### ISSUE THREAD

**Issue by ThomasWeiser** [elm-lang/elm-platform#41]
I can build the current master versions of elm-compiler and elm-package (and elm-make, elm-repl). After I make some changes in elm-compiler I want to rebuild it.

But when I go back to rebuild elm-compiler, cabal complains that elm-package is broken:

```
> cabal sandbox init --sandbox=.
> cd elm-compiler
> cabal sandbox init --sandbox=..
> cabal install -j
> cd ../elm-package
> cabal sandbox init --sandbox=..
> cabal install -j
> cd ../elm-compiler
> cabal install -j


Resolving dependencies...
cabal: Could not resolve dependencies:
trying: elm-compiler-0.15 (user goal)
next goal: elm-package (user goal)
rejecting: elm-package-0.5/installed-9a4... (package is broken)
[...]
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

I am no cabal expert, so I have no clue how to fix it.
I can only workaround by deleting all build artifacts and build from scratch.

It worked in 0.14.1.

**Comment by barksten** [comment]
I got a similar () error:
> Resolving dependencies...
cabal: Could not resolve dependencies:
trying: elm-compiler-0.15 (user goal)
trying: base-4.8.0.0/installed-901... (dependency of elm-compiler-0.15)
trying: edit-distance-0.2.1.2 (dependency of elm-compiler-0.15)
trying: edit-distance-0.2.1.2:-benchmark
rejecting: edit-distance-0.2.1.2:+splitbase (conflict:
base==4.8.0.0/installed-901..., edit-distance-0.2.1.2:splitbase => base>=3 &&
<4.8)
rejecting: edit-distance-0.2.1.2:-splitbase (conflict:
base==4.8.0.0/installed-901..., edit-distance-0.2.1.2:splitbase => base<3)
Dependency tree exhaustively searched.

**Comment by evancz** [comment]
I also run into this, but have started using a weird trick to get around it.

There is some metadata in a directory at the root of the sandbox, so I have a script that deletes `x86_.../elm-package-...` (where the ... are filled in with stuff, it's different on every platform I think) and then tries to compile.

I do not know how to work around it another way for now!

**Comment by ThomasWeiser** [comment]
Thanks, good to know!

**Comment by ajhager** [comment]
I am trying to find a fix for this. It is clear that when building elm-compiler after elm-package, cabal pulls in and builds elm-package 0.5 from Hackage, which pulls in a bunch of older conflicting dependencies. I've tried finding ANY package that might depend on elm-package 0.5, and tightening up the dependencies of every project in the elm platform, but no luck so far.

@evancz 's tip about removing the metadata works, but I could see it being a bit blocker for new contributors. I was almost discouraged from working on elm-compiler until I found this issue.

**Comment by jvoigtlaender** [comment]
Instead of
```
> cabal sandbox init --sandbox=.
> cd elm-compiler
> cabal sandbox init --sandbox=..
> cabal install -j
> cd ../elm-package
> cabal sandbox init --sandbox=..
> cabal install -j
> cd ../elm-compiler
> cabal install -j
```
you almost certainly want (for a workflow in which you want to change `elm-compiler` code at some point and have it reinstalled after that) something like this:
```
> cabal sandbox init --sandbox=.
> cabal sandbox add-source elm-compiler
> cabal sandbox add-source elm-package
> cabal install -j
[change some code in elm-compiler or in elm-package]
> cabal install -j
[change some further code somewhere]
> cabal install -j
...
```
See https://github.com/elm-lang/elm-platform/pull/55.

**Comment by ajhager** [comment]
Oh awesome, thank you. I will definitely give that a try.

**Comment by jvoigtlaender** [comment]
@ajhager, if you are still into this, actually rather give https://github.com/elm-lang/elm-platform/pull/55#issuecomment-135023780 a try.

**Comment by jvoigtlaender** [comment]
I think this issue can be closed. The way the now current `BuildFromSource.hs` works should fix what was the problem here.

**Comment by ThomasWeiser** [comment]
Thanks for fixing this!
As suggested by @jvoigtlaender I close this issue.
