### ISSUE TITLE
Elm-make failing on OSX using Elm-Platform-0.15.pkg

### ISSUE THREAD

**Issue by sgwizdak** [elm-lang/elm-platform#44]
Installed Elm from Elm-Platform-0.15.pkg on OSX 10.10.2.

 When attempting to build,

    HelloWorld.elm
    main = plainText "Hello World!"

with `elm-make HelloWorld.elm --output HelloWorld.html`

I'm getting,

    No versions of package 'elm-lang/core' were found!
    Is it spelled correctly?

Elm-repl, and elm-package also fail with the same error message. 

Additional notes: using ghc 7.10.1 and cabal 1.22.0.0 (https://ghcformacosx.github.io/) as Haskell Platform for osx 10.10 seems to be nearly unusable.

**Comment by sgwizdak** [comment]
Discovered `npm install --global elm`, and that installation works fine.

**Comment by evancz** [comment]
I don't think I have enough to debug what was going wrong here, so I am going to close this one. Sorry we were not more helpful, and I'm glad it got going anyway!
