### ISSUE TITLE
ELM_HOME not set by npm install -g elm

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-platform#46]
This causes the symptom that if you do `npm install -g elm` and then run `elm-reactor`, it 500s when attempting to fetch resources, with the following message:

```
A web handler threw an exception. Details:
user error (Unable to find the ELM_HOME environment variable when searching
for the _reactor/debug.js file.

If you installed Elm Platform with the Mac or Windows installer, it looks like
ELM_HOME was not set automatically. Look up how to set environment variables
on your platform and set ELM_HOME to the directory that contains Elm's static
files:

  * On Mac it is /usr/local/share/elm
  * On Windows it is one of the following:
      C:/Program Files/Elm Platform/0.15/share
      C:/Program Files (x86)/Elm Platform/0.15/share

If it seems like a more complex issue, please report it here:
    <https://github.com/elm-lang/elm-platform/issues>
)
```

After uninstalling the `npm` version and using the Mac installer, it worked as expected.

**Comment by evancz** [comment]
I actually do not know anything about the npm stuff. This was created by @kevva at [this repo](https://github.com/kevva/elm-bin) and @passy may also know more than me.

**Comment by rtfeldman** [comment]
Oh, sure...but I assume this is the correct place to raise the issue, yeah?

**Comment by kevva** [comment]
Nah, you should probably create it at https://github.com/kevva/elm-bin/issues/new.

**Comment by rtfeldman** [comment]
:+1:  Closing in favor of https://github.com/kevva/elm-bin/issues/13
