### ISSUE TITLE
Linux: elm-make expected to be in system $PATH

### ISSUE THREAD

**Issue by conklech** [elm-lang/elm-platform#47]
On Ubuntu, installing the `elm-*` binaries in someplace like `~/.cabal/bin` results in crashes with both `elm-repl` (evaluating anything, e.g. `x = 1`) and `elm-reactor` (opening an `.elm` file):

    elm-make: readProcessWithExitCode: runInteractiveProcess: exec: does not exist (No such file or directory)

I'm not sure how to read that error; I think it is failing to find `elm-make`.

The `runInteractiveProcess` docs/source [claim](https://hackage.haskell.org/package/process-1.2.3.0/docs/System-Process.html#v:RawCommand) that it looks in the directories specified by `$PATH`. In the interactive shell I'm running from, `elm-make` is on $PATH. I assume that something is changing  the environment variables in this context, but I don't know what it is. I'm not sufficiently at home in POSIX to suggest a resolution.

Moving the `elm-make` binary to `/usr/local/bin` fixes the problem, but that's not really a good solution; at any rate that's not what the Elm docs suggest.

For what it's worth, trying to set the path in `~/.profile` rather than `~/.bashrc` (as suggested by [this StackOverflow answer](http://unix.stackexchange.com/a/26059)) doesn't seem to change anything.

**Comment by evancz** [comment]
If you run the following, what does it give you?

```bash
echo $PATH
```

**Comment by conklech** [comment]
Sorry; I seem to have omitted essential information from the original report. (I recall being very confused.) I don't have that system available right now. It's buried in the original report that `elm-make` was on `$PATH`, by which I presumably meant that `echo $PATH` would have included `~/.cabal/bin`, where the elm binaries were.

If I remember correctly, I had installed GHC following [these instructions](https://www.haskell.org/downloads/linux), which call for adding `~/.cabal/bin` inter alia to `$PATH` via `~/.bashrc`. I'm pretty sure that `echo $PATH` would have included that directory.

**Comment by evancz** [comment]
If you used the BuildFromSource.hs script, it would not put things in ~/.cabal/bin because it uses sandboxes.

Did you get stuff working though? If so, I'd like to close this because I think it's going to be hard to figure out what went wrong and I'm not sure it's a general issue.

**Comment by conklech** [comment]
I don't recall how I installed it, sorry.

Closing for lack of reproduction.

**Comment by evancz** [comment]
Okay, no worries! Sorry you ran into trouble :/

**Comment by teppix** [comment]
I had the exact same issue, and I thought I'd write it down in case anyone else ends up here when searching for the solution.

At least for me, the problem was that I had included the tilde sign in the path variable. bash expands this when searching the path, so it finds the binaries just fine, but elm doesn't.

The solution is to make sure that the PATH contains only absolute paths, and no tilde signs.

Apparently bash does not expand ~ when inside a quote, so this won't work with elm:
PATH="~/.cabal/bin"

However, both of these seems to work:
PATH=~/.cabal/bin
PATH="$HOME/.cabal/bin"

Hope this helps!

**Comment by r41d** [comment]
Can confirm that an absolute path instead of a relative path (~) in PATH fixes this.
Wouldn't have thought of thought, thx for the fix @teppix!

**Comment by revereche** [comment]
Just wanted to add that I encountered this problem installing via npm, and was able to fix it by adding $HOME/.npm-global/bin to my path.

**Comment by thmzlt** [comment]
Also ran into this. Using `$HOME` and defining `$PATH` without quotes to fix it.

**Comment by brundonsmith** [comment]
Is there any way this can be fixed, or a more helpful error message can be shown? Two years later and I just ran into this because I had `export PATH="~/.npm-global/bin:${PATH}"` in my bash profile, which yielded this cryptic error when I tried to evaluate `"hello"` in the repl:
```
elm-repl: elm-make: readCreateProcessWithExitCode: runInteractiveProcess: exec: does not exist (No such file or directory)
```
