### ISSUE TITLE
BuildFromSource.hs 0.15 fails

### ISSUE THREAD

**Issue by Fresheyeball** [elm-lang/elm-platform#48]
So I am trying to build from source so I can have elm on linux, but having trouble.

```
cabal-install version 1.16.0.2
using version 1.16.0 of the Cabal library 
```

I've also done my best to reset my environment with

```
rm -r ~/.cabal ~/.ghc
cabal update
```

but no dice. Every time I get the following error 

```
Failed to install terminfo-0.4.0.1
Last 10 lines of the build log ( /home/isaac/.cabal/logs/terminfo-0.4.0.1.log
):
checking for unistd.h... yes
checking ncurses.h usability... no
checking ncurses.h presence... no
checking for ncurses.h... no
checking curses.h usability... no
checking curses.h presence... no
checking for curses.h... no
configure: error: in `/tmp/terminfo-0.4.0.1-36426/terminfo-0.4.0.1':
configure: error: curses headers could not be found, so this package cannot be
built
See `config.log' for more details
cabal: Error: some packages failed to install:
elm-repl-0.4 depends on terminfo-0.4.0.1 which failed to install.
haskeline-0.7.2.1 depends on terminfo-0.4.0.1 which failed to install.
terminfo-0.4.0.1 failed during the configure step. The exception was:
ExitFailure 1
```

any idea what's wrong?

**Comment by jvoigtlaender** [comment]
Looks like you are missing some system library. The "curses headers could not be found" indicates so. Probably you need to first install something in your system. Should be something like "libncurses5-dev", maybe another number than "5".

But: 

Anyway, "so I can have elm on linux" does not necessarily mean you have to install from source. You could use the npm installer. Something like `apt-get install npm` followed by `npm install elm` should get you to a working version much quicker.

**Comment by Fresheyeball** [comment]
Oh, if its on npm, I will definitely do that over fighting with the lovely and magnanimous `cabal`. In that case my issue is that the `npm` option is not clearly stated on `elm-lang.org`. It should be documented here http://elm-lang.org/Install.elm me thinks.

**Comment by jvoigtlaender** [comment]
Maybe it should. Possible reason it isn't is that the npm installer is not made by Evan himself.

Anyway, once you have it npm-installed, you need to set the `ELM_HOME` environment variable to the directory `share` inside `node_modules/elm` (somewhere in the npm directory structure). (And, of course, the binaries, probably in `.../node_modules/elm/bin`, should be on your path.)

**Comment by jvoigtlaender** [comment]
Close this via https://github.com/elm-lang/elm-lang.org/pull/295?

**Comment by evancz** [comment]
@Fresheyeball, did you get it working?

I just merged in @jvoigtlaender's change so people don't need to have the same rough experience as you. Sorry for the trouble!

**Comment by Fresheyeball** [comment]
@evancz npm worked great for me. I'd still like to build from source (just cuz), but I'll get that later.

**Comment by rtfeldman** [comment]
Also the `npm` installation has worked well (modulo intermittent `hGetContents` errors, though unclear what the actual culprit is there) on our CI server at work.
