### ISSUE TITLE
Fix elm-doc

### ISSUE THREAD

**Issue by thSoft** [elm-lang/elm-platform#50]
`cd installers/mac; ./make-installer.sh master` fails:
```...
Installed elm-repl-0.4.1
Updating documentation index /Users/thsoft/Library/Haskell/doc/index.html
cp: Elm-Platform/master/bin/elm-doc: No such file or directory
```

Versions:
* OS X 10.10.3
* ghc 7.10.1
* elm-platform 5134bbbf70345698b1c6ea2df9d48d4d4aab65bf

**Comment by evancz** [comment]
Ah, yeah, `elm-doc` is in limbo at the moment. That seems like the root cause of this.

**Comment by thSoft** [comment]
I deleted elm-doc from the script, and successfully installed Elm from the resulting .pkg file, but now ``elm-package publish|bump|diff``` fails with:

```
elm-package-unwrapped: elm-doc: readCreateProcessWithExitCode: runInteractiveProcess: exec: does not exist (No such file or directory)
```

**Comment by evancz** [comment]
This should be sorted out now, thanks for the report!
