### ISSUE TITLE
Proposal: elm test warning

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-platform#51]
If you do `npm install -g elm-test` you'll be able to run `elm test` and have it work nicely.

However, if you have installed the Elm Platform but have not installed `elm-test` via `npm`, you may be surprised to find that running `elm test Tests.elm` yields an error. The error message won't give you much clue what the problem is, though; it'll just say that it doesn't know how to `elm test`.

I propose that we improve this user experience by making the `elm` binary aware of this likely problem. It could have a special-case error message for the case where the user requests `elm test` but no `elm-test` binary is found on the PATH. It could say something like:

```
elm test is not currently installed. To install it, please see these instructions:
    http://elm-lang.org/testing
```

**Comment by maxsnew** [comment]
Here's the error message I get right now:
```
Could not find command `test`. Maybe there is a typo?

Default commands include:

  make      Compile an Elm file or project into JS or HTML
  package   Manage packages from <http://package.elm-lang.org>
  reactor   Develop with compile-on-refresh and time-travel debugging
  repl      A REPL for running individual expressions

When you try to run the command `test` we actually search for an
  executable named elm-test. Are you able to run elm-test?
  Is it on your PATH?
```

It says at the bottom that it looks for `elm-test` on your PATH. That seems like reasonable behavior to me. Maybe this issue is out of date?

**Comment by rtfeldman** [comment]
I was specifically suggesting special-casing it for `elm-test`, which I think is reasonable because although it is technically an unofficial third-party tool, it's the de facto way to write tests in Elm, which is a super common desire.

**Comment by rtfeldman** [comment]
Closing in favor of https://github.com/elm-lang/elm-compiler/issues/1369
