### ISSUE TITLE
Unable to install on Linux using npm

### ISSUE THREAD

**Issue by UnboxedType** [elm-lang/elm-platform#57]
$ uname -a
Linux apollo 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ npm --version
1.3.6

$ npm install elm 
npm http GET https://registry.npmjs.org/elm
npm http 304 https://registry.npmjs.org/elm
npm http GET https://registry.npmjs.org/logalot
npm http GET https://registry.npmjs.org/async-each-series
... (alot more)

> elm@2.0.0 postinstall /home/user/node_modules/elm
> node lib/install.js

  ✖ Request to https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz failed
  ✖ elm pre-build test failed
  ✖ Request to https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz failed
  ✖ elm-make pre-build test failed
  ✖ Request to https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz failed
  ✖ elm-package pre-build test failed
  ✖ Request to https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz failed
  ✖ elm-reactor pre-build test failed
  ✖ Request to https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz failed
  ✖ elm-repl pre-build test failed

elm@2.0.0 node_modules/elm
├── async-each-series@0.1.1
├── logalot@2.1.0 (figures@1.3.5, squeak@1.2.0)
└── bin-wrapper@3.0.2 (lazy-req@1.0.0, os-filter-obj@1.0.3, each-async@1.1.1, bin-check@2.0.0, bin-version-check@2.1.0, download@4.2.0)

I found a similar issue https://github.com/kevva/elm-bin/issues/26, but it is stated that the problem has been fixed. 

I have tried to wget this file and it works. I am sitting behind corporate proxy firewall, can this be an issue? 

Any help is appreciated.
Thanks!

**Comment by evancz** [comment]
I think the elm-bin folks will know better. Does it fail if you run it with `sudo npm install elm --global`?

Otherwise I don't know how to help or manage the repo that seems to be the culprit unfortunately :/
