### ISSUE TITLE
No licence information in the Windows installer

### ISSUE THREAD

**Issue by grzegorzbalcerek** [elm-lang/elm-platform#58]
Hi,
I noticed that the windows installer do not show any license information.
It also do not create any license file.
Not sure if that is deliberate or just a mistake but I suppose it is just an omission.
Note, that for certain institutions using a software with no licensing information might be problematic (or not acceptable) and thus might potentially prevent adoption because of formal reasons (although I am not sure how probable such a situation really is).

**Comment by rtfeldman** [comment]
Thanks for bringing this up, but with so many higher-priority things to work on, I don't think this would be a justifiable change unless it were solving a serious, specific problem.

As such, I'm going to close the issue.
