### ISSUE TITLE
Tracking installation issues

### ISSUE THREAD

**Issue by eeue56** [elm-lang/elm-platform#59]
This issue exists to collect data on the number of people having problems installing Elm and which platforms they have the issues on. The current know routes are recorded here:

route | OS | Version | bits | status
---|---------|------|-----------|-----------
installer | Windows | * | * | ✓
 | OSX | * | * | ✓
npm | * | * | * | elm-reactor needs ELM_HOME
 | Ubuntu | * | 32 | binary is 64-bit
from source | * | * | * | cabal hell

Based on website traffic, we can roughly guess that 50% of users are on OSX, 30% are on windows, and 20% are on some flavor of Linux.

I have removed the `npm` installer from the typical install path, so right now, Linux folks are building from source. I'd be interested to get the breakdown of users within Linux. I have a suspicion that Ubuntu or variations of Debian account for the majority of folks there.

If that is true, my priority would be trying to get `npm install -g elm` working there without the ELM_HOME issue. I think this is nicer than `apt-get install` in certain ways. I have made some updates to `elm-reactor` such that ELM_HOME will no longer be needed by anyone anywhere. I have also taken basic steps to see if I can build the compiler on a 32-bit version of Debian or Ubuntu, but ran into issues getting GHC and cabal in order (surprise!)

## Reporting Additional Information for this Issue

If you are having issues that are not captured by this table, please post:

* Your OS with the version number
* Number of bits
* Your installation method
* The error encountered

For example,

> * OS: Ubuntu 13.04
> * bits: 32
> * route: BuildFromSource.hs
> * error: ENOENT not found /usr/lib/elm/vendor/elm-make 

As per https://github.com/elm-lang/elm-plans/issues/21

**Comment by evancz** [comment]
Alright, I did so much changes that I just opened up #60 that covers it all.
