### ISSUE TITLE
Deprecate GHC 7.8 builds for compatibility with next OS X release

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-platform#75]
Building with GHC 7.8 results in Elm binaries that do not work with the upcoming release of OS X ("El Capitan" - slated for [a "fall 2015" release](http://www.macrumors.com/roundup/os-x-10-11/) although Apple may announce a formal release date at a [press event scheduled for September 9](http://osxdaily.com/2015/08/27/apple-event-september-9-siri-give-me-hint/)). My coworker has already experienced this; he is running the El Capitan preview and the latest 0.15.1 Elm binaries [do not work for him](https://github.com/elm-lang/elm-package/issues/109#issuecomment-128533917).

Building with GHC 7.10 [evidently fixes this](https://github.com/elm-lang/elm-package/issues/109#issuecomment-124096929), but the fix will not be backported to GHC 7.8.

This repo's README currently says:

> Developers typically build with GHC 7.8 but as of 0.15.1 things should build with GHC 7.10 as well.

Considering this will soon result in incompatible OS X binaries, it certainly appears that it will become necessary to mandate building with GHC 7.10 only. Perhaps beginning in the 0.16 release?

Switching to 7.10-only builds should fix https://github.com/elm-lang/elm-package/issues/109

**Comment by jvoigtlaender** [comment]
I'm all for moving to GHC 7.10.2.

What you link to also means that people on OS X will not be able to build Elm 0.15 (or earlier) in the future. We can make sure that 0.15.1 and onwards are fine, but making older Elm releases compatible with new GHC versions is a lost cause. See e.g. [here](https://github.com/elm-lang/elm-compiler/issues/926#issuecomment-136027010).

**Comment by rtfeldman** [comment]
That seems fine. Pretty sure if you're intentionally building an older version from source, you can expect some unusual workarounds to be fair game. ;)

**Comment by evancz** [comment]
I've done this on a few repos, so this has effectively happened already.
