### ISSUE TITLE
Installation Failure: Resource Vanished Downloading Zipball

### ISSUE THREAD

**Issue by wilhelmson** [elm-lang/elm-platform#76]
* OS: Antergos (Arch 4.1.6-1)
* Bits: 64
* Path: BuildFromSource
* Error: see below
* GHC: 7.10.1
* Cabal: 1.22.2.0

Trying to install 0.15.1, I make it as far as building `elm-reacto-0.3.2` but the process fails with the following:

```
Linking dist/dist-sandbox-6432d1ce/build/elm-reactor/elm-reactor ...
Failed to build SideBar.elm

Downloading elm-lang/core
failed with 'InternalIOException recv: resource vanished (Connection reset by peer)' when sending request to
    <http://github.com/elm-lang/core/zipball/2.1.0/>

Custom build step: creating and collecting all static resources
cabal: Error: some packages failed to install:
elm-reactor-0.3.2 failed during the building phase. The exception was:
ExitFailure 1
```

There are also a few warnings while compling `backend/Compile.hs`, but I imagine they're not relevant.

**Comment by jvoigtlaender** [comment]
The compile warnings shouldn't be relevant.

It seems all the executables were successfully built (including the executable for `elm-reactor`). The step where it fails is when some static resources are to be compiled (from Elm to JavaScript, using the just built Elm compiler), for eventual use in the `elm-reactor`.

I have no idea what the error could be. It could be completely unrelated to Elm. Was your machine having general Internet connection problems when this happened? Are you behind some sort of firewall or whatever that could interfere with the `elm-make` executable (which is what is being run in that "Custom build step") trying to download stuff from GitHub?

Can you try to just run `elm-make` (without any involvement of the reactor) on a simple example file? Or even just something like `elm-package install` in an empty directory? Do you get an error then as well?

**Comment by wilhelmson** [comment]
I thought it might be related to connection issues based on the output. I wasn't having any issues with connectivity at the time; was able to download the files from the repo through my browser. I don't believe I'm behind any firewall.

**Comment by wilhelmson** [comment]
Sorry for the close/reopen...got click happy.

**Comment by wilhelmson** [comment]
Sure enough, it was a something to do with the network I was on. Just tried on my home network and everything went fine. Thanks.
