### ISSUE TITLE
proposal - Batch update _and_ add operation in records

### ISSUE THREAD

**Issue by Warry** [elm-lang/elm-platform#78]
Hi there,

Currently we can batch updates operations on a record. I was wondering if there was a technical reason not to batch add operation as well (on top of my head: type inference)? Being so, we could be able to "override" default fields in a record while extending it.

``` elm
type alias Foo a =
  { a | foo : Int }

type alias Bar a =
  { a | bar : String }

type alias FooBar =
  Foo (Bar {})

deftFoo : Foo {}
deftFoo = { foo = 8 }

-- This works, but is not very scalable
toto : FooBar
toto =
  let x = { deftFoo | bar = "bar" }
  in { x | foo <- 8 }

-- We can batch "updates":
tata : FooBar
tata =
  { toto | bar <- "foobar"
         , foo <- 42
         }

-- This is the proposal, also batching "add" (DO NOT COMPILE)
tutu : FooBar
tutu =
 { deftFoo | bar = "foobar"
           , foo <- 42
           }
```

**Comment by rtfeldman** [comment]
I believe https://github.com/elm-lang/elm-compiler/issues/985 was accepted and add operations have been removed in `master`, but I could be wrong. :smile:

**Comment by Warry** [comment]
I should have asked on the ML before. Didn't realised that elm-compiler was also a place for this duscussions.
