### ISSUE TITLE
Elm static analysis and dynamic execution (in Elm)

### ISSUE THREAD

**Issue by jcmoore** [elm-lang/elm-platform#90]
Elm looks very interesting (so much so that I may try porting a polymer framework of components to it), but I'm interested in knowing to what extent I can create functions/values/modules from strings, and parse/analyze elm source-code in Elm natively.

Despite the shortcomings of languages like Javascript and Lua, they have pretty strong facilities for analyzing and executing user-provided code at runtime.  I'm very new to the ML world, but it looks like Haskell can do much of the same.  Is there a way to create runtime usable resources from strings of Elm?  Is there a plan to port the compiler (and type inferencing mechanisms) to Elm?  Is that going to become my 2016 project?

**Comment by jvoigtlaender** [comment]
There have been various discussions on the mailing list about both aspects. A recent one is [this thread](https://groups.google.com/d/msg/elm-discuss/Td0G-SA577g/RggbE8afCQAJ).

Generally, asking that kind of question on the mailing list is likely going to give more useful results (including further pointers to earlier discussions) than an issue here in this repository.

**Comment by evancz** [comment]
I don't have near-term plans for stuff like Template Haskell, but I am aware of it and things like MetaML and MetaOCaml. I have some very modest "macro" ideas that I think are plausible as well. It'd be interesting to get an idea of what you are interested in specifically to help guide those thoughts though. Do you mind sharing your particular vision of things on the elm-dev mailing list?
