### ISSUE TITLE
Npm installer for elm stuck

### ISSUE THREAD

**Issue by letronje** [elm-lang/elm-platform#96]
I ran ```npm install --global elm --verbose```
```( npm --version ==> 2.14.7 , node --version  ==> v4.2.1 )```

the installer is stuck, here are the last few lines it printed

```
npm info install elm@2.0.0
npm info postinstall elm@2.0.0

> elm@2.0.0 postinstall /home/letronje/.nvm/versions/node/v4.2.1/lib/node_modules/elm
> node lib/install.js
```

What do I do ?

**Comment by jvoigtlaender** [comment]
Open an issue at https://github.com/kevva/elm-bin?

Probably after looking through open and closed issues over there first, to see whether somebody else already had the same problem before you.

**Comment by letronje** [comment]
Network issue, sorry for the trouble. Closing this.
