### ISSUE TITLE
OSX Installer: /usr/local/bin does not allow read or execute for anyone except owner

### ISSUE THREAD

**Issue by williamwilson** [elm-lang/elm-platform#97]
OS: OSX 10.11.1
bits: 64
route: mac installer
error: unable to execute any of the elm binaries after installation completes successfully

This was a rather clean OSX install and I did not yet have a /usr/local/bin directory.  The installer created it, however the installer did not give read or execute access to anyone except the owner.  A simple chmod 755 on /usr/local/bin fixed the issue.

**Comment by jvoigtlaender** [comment]
Is this still happening with the current version of Elm?

**Comment by evancz** [comment]
I'd feel uncomfortable running `chmod` on peoples stuff. I suspect people set it different ways for different reasons. I'd want to get some consensus on elm-dev or on the Elm slack channel before making a change like this. Don't know enough to be confident what's the right thing!
